// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// An AwsS3Data resource can be a data source, but not a data sink.
/// In an AwsS3Data resource, an object's name is the S3 object's key name.
public struct AwsS3Data: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. S3 Bucket name (see
  /// [Creating a
  /// bucket](https://docs.aws.amazon.com/AmazonS3/latest/dev/create-bucket-get-location-example.html)).
  public var bucketName: Swift.String = Swift.String()

  /// Input only. AWS access key used to sign the API requests to the AWS S3
  /// bucket. Permissions on the bucket must be granted to the access ID of the
  /// AWS access key.
  ///
  /// For information on our data retention policy for user credentials, see
  /// [User credentials](/storage-transfer/docs/data-retention#user-credentials).
  public var awsAccessKey: AwsAccessKey? = nil

  /// Root path to transfer objects.
  ///
  /// Must be an empty string or full path name that ends with a '/'. This field
  /// is treated as an object prefix. As such, it should generally not begin with
  /// a '/'.
  public var path: Swift.String = Swift.String()

  /// The Amazon Resource Name (ARN) of the role to support temporary
  /// credentials via `AssumeRoleWithWebIdentity`. For more information about
  /// ARNs, see [IAM
  /// ARNs](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-arns).
  ///
  /// When a role ARN is provided, Transfer Service fetches temporary
  /// credentials for the session using a `AssumeRoleWithWebIdentity` call for
  /// the provided role using the
  /// [GoogleServiceAccount][google.storagetransfer.v1.GoogleServiceAccount] for
  /// this project.
  ///
  /// [google.storagetransfer.v1.GoogleServiceAccount]: <doc:GoogleServiceAccount>
  public var roleArn: Swift.String = Swift.String()

  /// Optional. The CloudFront distribution domain name pointing to this bucket,
  /// to use when fetching.
  ///
  /// See
  /// [Transfer from S3 via
  /// CloudFront](https://cloud.google.com/storage-transfer/docs/s3-cloudfront)
  /// for more information.
  ///
  /// Format: `https://{id}.cloudfront.net` or any valid custom domain. Must
  /// begin with `https://`.
  public var cloudfrontDomain: Swift.String = Swift.String()

  /// Optional. The Resource name of a secret in Secret Manager.
  ///
  /// AWS credentials must be stored in Secret Manager in JSON format:
  ///
  /// {
  ///  "access_key_id": "ACCESS_KEY_ID",
  ///  "secret_access_key": "SECRET_ACCESS_KEY"
  /// }
  ///
  /// [GoogleServiceAccount][google.storagetransfer.v1.GoogleServiceAccount] must
  /// be granted `roles/secretmanager.secretAccessor` for the resource.
  ///
  /// See [Configure access to a source: Amazon S3]
  /// (https://cloud.google.com/storage-transfer/docs/source-amazon-s3#secret_manager)
  /// for more information.
  ///
  /// If `credentials_secret` is specified, do not specify
  /// [role_arn][google.storagetransfer.v1.AwsS3Data.role_arn] or
  /// [aws_access_key][google.storagetransfer.v1.AwsS3Data.aws_access_key].
  ///
  /// Format: `projects/{project_number}/secrets/{secret_name}`
  ///
  /// [google.storagetransfer.v1.AwsS3Data.aws_access_key]: <doc:AwsS3Data/awsAccessKey>
  /// [google.storagetransfer.v1.AwsS3Data.role_arn]: <doc:AwsS3Data/roleArn>
  /// [google.storagetransfer.v1.GoogleServiceAccount]: <doc:GoogleServiceAccount>
  public var credentialsSecret: Swift.String = Swift.String()

  public var privateNetwork: OneOf_PrivateNetwork? = nil

  /// Initialize a new instance of `AwsS3Data`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AwsS3Data().with { $0.bucketName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case bucketName = "bucketName"
    case awsAccessKey = "awsAccessKey"
    case path = "path"
    case roleArn = "roleArn"
    case cloudfrontDomain = "cloudfrontDomain"
    case credentialsSecret = "credentialsSecret"
    case managedPrivateNetwork = "managedPrivateNetwork"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.bucketName = try container.decode(Swift.String.self, forKey: .bucketName)
    self.awsAccessKey = try container.decodeIfPresent(AwsAccessKey.self, forKey: .awsAccessKey)
    self.path = try container.decode(Swift.String.self, forKey: .path)
    self.roleArn = try container.decode(Swift.String.self, forKey: .roleArn)
    self.cloudfrontDomain = try container.decode(Swift.String.self, forKey: .cloudfrontDomain)
    self.credentialsSecret = try container.decode(Swift.String.self, forKey: .credentialsSecret)

    var privateNetwork: OneOf_PrivateNetwork? = nil
    let privateNetworkCheckAndSet = {
      if privateNetwork != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'privateNetwork'"))
      }
      privateNetwork = $0
    }
    if let managedPrivateNetwork = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .managedPrivateNetwork)
    {
      try privateNetworkCheckAndSet(.managedPrivateNetwork(managedPrivateNetwork))
    }
    self.privateNetwork = privateNetwork
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.bucketName, forKey: .bucketName)
    try container.encode(self.awsAccessKey, forKey: .awsAccessKey)
    try container.encode(self.path, forKey: .path)
    try container.encode(self.roleArn, forKey: .roleArn)
    try container.encode(self.cloudfrontDomain, forKey: .cloudfrontDomain)
    try container.encode(self.credentialsSecret, forKey: .credentialsSecret)

    if let choice = self.privateNetwork {
      switch choice {
      case .managedPrivateNetwork(let value):
        try container.encode(value, forKey: .managedPrivateNetwork)
      }
    }
  }

  public enum OneOf_PrivateNetwork: Codable, Equatable, Sendable {
    /// Egress bytes over a Google-managed private network.
    /// This network is shared between other users of Storage Transfer Service.
    case managedPrivateNetwork(Swift.Bool)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.AwsS3Data"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
