// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An AwsS3CompatibleData resource.
public struct AwsS3CompatibleData: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Specifies the name of the bucket.
  public var bucketName: Swift.String = Swift.String()

  /// Specifies the root path to transfer objects.
  ///
  /// Must be an empty string or full path name that ends with a '/'. This
  /// field is treated as an object prefix. As such, it should generally not
  /// begin with a '/'.
  public var path: Swift.String = Swift.String()

  /// Required. Specifies the endpoint of the storage service.
  public var endpoint: Swift.String = Swift.String()

  /// Specifies the region to sign requests with. This can be left blank if
  /// requests should be signed with an empty region.
  public var region: Swift.String = Swift.String()

  /// Specifies the metadata of the S3 compatible data provider. Each provider
  /// may contain some attributes that do not apply to all S3-compatible data
  /// providers. When not specified, S3CompatibleMetadata is used by default.
  public var dataProvider: OneOf_DataProvider? = nil

  /// Initialize a new instance of `AwsS3CompatibleData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AwsS3CompatibleData().with { $0.bucketName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case bucketName = "bucketName"
    case path = "path"
    case endpoint = "endpoint"
    case region = "region"
    case s3Metadata = "s3Metadata"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.bucketName = try container.decode(Swift.String.self, forKey: .bucketName)
    self.path = try container.decode(Swift.String.self, forKey: .path)
    self.endpoint = try container.decode(Swift.String.self, forKey: .endpoint)
    self.region = try container.decode(Swift.String.self, forKey: .region)

    var dataProvider: OneOf_DataProvider? = nil
    let dataProviderCheckAndSet = {
      if dataProvider != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'dataProvider'"))
      }
      dataProvider = $0
    }
    if let s3Metadata = try container.decodeIfPresent(
      S3CompatibleMetadata?.self, forKey: .s3Metadata)
    {
      try dataProviderCheckAndSet(.s3Metadata(s3Metadata))
    }
    self.dataProvider = dataProvider
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.bucketName, forKey: .bucketName)
    try container.encode(self.path, forKey: .path)
    try container.encode(self.endpoint, forKey: .endpoint)
    try container.encode(self.region, forKey: .region)

    if let choice = self.dataProvider {
      switch choice {
      case .s3Metadata(let value):
        try container.encode(value, forKey: .s3Metadata)
      }
    }
  }

  /// Specifies the metadata of the S3 compatible data provider. Each provider
  /// may contain some attributes that do not apply to all S3-compatible data
  /// providers. When not specified, S3CompatibleMetadata is used by default.
  public enum OneOf_DataProvider: Codable, Equatable, Sendable {
    /// A S3 compatible metadata.
    indirect case s3Metadata(S3CompatibleMetadata?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.AwsS3CompatibleData"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
