// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An AzureBlobStorageData resource can be a data source, but not a data sink.
/// An AzureBlobStorageData resource represents one Azure container. The storage
/// account determines the [Azure
/// endpoint](https://docs.microsoft.com/en-us/azure/storage/common/storage-create-storage-account#storage-account-endpoints).
/// In an AzureBlobStorageData resource, a blobs's name is the [Azure Blob
/// Storage blob's key
/// name](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#blob-names).
public struct AzureBlobStorageData: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the Azure Storage account.
  public var storageAccount: Swift.String = Swift.String()

  /// Required. Input only. Credentials used to authenticate API requests to
  /// Azure.
  ///
  /// For information on our data retention policy for user credentials, see
  /// [User credentials](/storage-transfer/docs/data-retention#user-credentials).
  public var azureCredentials: AzureCredentials? = nil

  /// Required. The container to transfer from the Azure Storage account.
  public var container: Swift.String = Swift.String()

  /// Root path to transfer objects.
  ///
  /// Must be an empty string or full path name that ends with a '/'. This field
  /// is treated as an object prefix. As such, it should generally not begin with
  /// a '/'.
  public var path: Swift.String = Swift.String()

  /// Optional. The Resource name of a secret in Secret Manager.
  ///
  /// The Azure SAS token must be stored in Secret Manager in JSON format:
  ///
  /// {
  ///  "sas_token" : "SAS_TOKEN"
  /// }
  ///
  /// [GoogleServiceAccount][google.storagetransfer.v1.GoogleServiceAccount] must
  /// be granted `roles/secretmanager.secretAccessor` for the resource.
  ///
  /// See [Configure access to a source: Microsoft Azure Blob Storage]
  /// (https://cloud.google.com/storage-transfer/docs/source-microsoft-azure#secret_manager)
  /// for more information.
  ///
  /// If `credentials_secret` is specified, do not specify
  /// [azure_credentials][google.storagetransfer.v1.AzureBlobStorageData.azure_credentials].
  ///
  /// Format: `projects/{project_number}/secrets/{secret_name}`
  ///
  /// [google.storagetransfer.v1.AzureBlobStorageData.azure_credentials]: <doc:AzureBlobStorageData/azureCredentials>
  /// [google.storagetransfer.v1.GoogleServiceAccount]: <doc:GoogleServiceAccount>
  public var credentialsSecret: Swift.String = Swift.String()

  /// Optional. Federated identity config of a user registered Azure application.
  ///
  /// If `federated_identity_config` is specified, do not specify
  /// [azure_credentials][google.storagetransfer.v1.AzureBlobStorageData.azure_credentials]
  /// or
  /// [credentials_secret][google.storagetransfer.v1.AzureBlobStorageData.credentials_secret].
  ///
  /// [google.storagetransfer.v1.AzureBlobStorageData.azure_credentials]: <doc:AzureBlobStorageData/azureCredentials>
  /// [google.storagetransfer.v1.AzureBlobStorageData.credentials_secret]: <doc:AzureBlobStorageData/credentialsSecret>
  public var federatedIdentityConfig: AzureBlobStorageData.FederatedIdentityConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AzureBlobStorageData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureBlobStorageData().with { $0.storageAccount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let storageAccount = CodingKeys(stringValue: "storageAccount")
    static let azureCredentials = CodingKeys(stringValue: "azureCredentials")
    static let container = CodingKeys(stringValue: "container")
    static let path = CodingKeys(stringValue: "path")
    static let credentialsSecret = CodingKeys(stringValue: "credentialsSecret")
    static let federatedIdentityConfig = CodingKeys(stringValue: "federatedIdentityConfig")

    static let _knownKeys: Set<Swift.String> = [
      "storageAccount",
      "azureCredentials",
      "container",
      "path",
      "credentialsSecret",
      "federatedIdentityConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .storageAccount) {
      self.storageAccount = value
    }
    self.azureCredentials = try container.decodeIfPresent(
      AzureCredentials.self, forKey: .azureCredentials)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .container) {
      self.container = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .path) {
      self.path = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .credentialsSecret) {
      self.credentialsSecret = value
    }
    self.federatedIdentityConfig = try container.decodeIfPresent(
      AzureBlobStorageData.FederatedIdentityConfig.self, forKey: .federatedIdentityConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.storageAccount, forKey: .storageAccount)
    try container.encodeIfPresent(self.azureCredentials, forKey: .azureCredentials)
    try container.encode(self.container, forKey: .container)
    try container.encode(self.path, forKey: .path)
    try container.encode(self.credentialsSecret, forKey: .credentialsSecret)
    try container.encodeIfPresent(self.federatedIdentityConfig, forKey: .federatedIdentityConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The identity of an Azure application through which Storage Transfer Service
  /// can authenticate requests using Azure workload identity federation.
  ///
  /// Storage Transfer Service can issue requests to Azure Storage through
  /// registered Azure applications, eliminating the need to pass credentials to
  /// Storage Transfer Service directly.
  ///
  /// To configure federated identity, see
  /// [Configure access to Microsoft Azure
  /// Storage](https://cloud.google.com/storage-transfer/docs/source-microsoft-azure#option_3_authenticate_using_federated_identity).
  public struct FederatedIdentityConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The client (application) ID of the application with federated
    /// credentials.
    public var clientId: Swift.String = Swift.String()

    /// Required. The tenant (directory) ID of the application with federated
    /// credentials.
    public var tenantId: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `FederatedIdentityConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FederatedIdentityConfig().with { $0.clientId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientId = CodingKeys(stringValue: "clientId")
      static let tenantId = CodingKeys(stringValue: "tenantId")

      static let _knownKeys: Set<Swift.String> = [
        "clientId",
        "tenantId",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientId) {
        self.clientId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tenantId) {
        self.tenantId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.clientId, forKey: .clientId)
      try container.encode(self.tenantId, forKey: .tenantId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.storagetransfer.v1.AzureBlobStorageData.FederatedIdentityConfig"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.AzureBlobStorageData"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
