// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Specifies the request passed to CreateAgentPool.
public struct CreateAgentPoolRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The ID of the Google Cloud project that owns the
  /// agent pool.
  public var projectId: Swift.String = Swift.String()

  /// Required. The agent pool to create.
  public var agentPool: AgentPool? = nil

  /// Required. The ID of the agent pool to create.
  ///
  /// The `agent_pool_id` must meet the following requirements:
  ///
  /// *   Length of 128 characters or less.
  /// *   Not start with the string `goog`.
  /// *   Start with a lowercase ASCII character, followed by:
  ///     *   Zero or more: lowercase Latin alphabet characters, numerals,
  ///         hyphens (`-`), periods (`.`), underscores (`_`), or tildes (`~`).
  ///     *   One or more numerals or lowercase ASCII characters.
  ///
  /// As expressed by the regular expression:
  /// `^(?!goog)[a-z]([a-z0-9-._~]*[a-z0-9])?$`.
  public var agentPoolId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateAgentPoolRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateAgentPoolRequest().with { $0.projectId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let projectId = CodingKeys(stringValue: "projectId")
    static let agentPool = CodingKeys(stringValue: "agentPool")
    static let agentPoolId = CodingKeys(stringValue: "agentPoolId")

    static let _knownKeys: Set<Swift.String> = [
      "projectId",
      "agentPool",
      "agentPoolId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    self.agentPool = try container.decodeIfPresent(AgentPool.self, forKey: .agentPool)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .agentPoolId) {
      self.agentPoolId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encodeIfPresent(self.agentPool, forKey: .agentPool)
    try container.encode(self.agentPoolId, forKey: .agentPoolId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.CreateAgentPoolRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
