// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// A summary of errors by error code, plus a count and sample error log
/// entries.
public struct ErrorSummary: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required.
  public var errorCode: GoogleRpc.Code = GoogleRpc.Code()

  /// Required. Count of this type of error.
  public var errorCount: Swift.Int64 = Swift.Int64()

  /// Error samples.
  ///
  /// At most 5 error log entries are recorded for a given
  /// error code for a single transfer operation.
  public var errorLogEntries: [ErrorLogEntry] = []

  /// Initialize a new instance of `ErrorSummary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ErrorSummary().with { $0.errorCode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.ErrorSummary"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
