// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Specifies the Event-driven transfer options. Event-driven transfers listen to
/// an event stream to transfer updated files.
public struct EventStream: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Specifies a unique name of the resource such as AWS SQS
  /// ARN in the form 'arn:aws:sqs:region:account_id:queue_name',
  /// or Pub/Sub subscription resource name in the form
  /// 'projects/{project}/subscriptions/{sub}'.
  public var name: Swift.String = Swift.String()

  /// Specifies the date and time that Storage Transfer Service starts
  /// listening for events from this stream. If no start time is specified or
  /// start time is in the past, Storage Transfer Service starts listening
  /// immediately.
  public var eventStreamStartTime: GoogleCloudWKT.Timestamp? = nil

  /// Specifies the data and time at which Storage Transfer Service stops
  /// listening for events from this stream. After this time, any transfers in
  /// progress will complete, but no new transfers are initiated.
  public var eventStreamExpirationTime: GoogleCloudWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `EventStream`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EventStream().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let eventStreamStartTime = CodingKeys(stringValue: "eventStreamStartTime")
    static let eventStreamExpirationTime = CodingKeys(stringValue: "eventStreamExpirationTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "eventStreamStartTime",
      "eventStreamExpirationTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.eventStreamStartTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .eventStreamStartTime)
    self.eventStreamExpirationTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .eventStreamExpirationTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.eventStreamStartTime, forKey: .eventStreamStartTime)
    try container.encodeIfPresent(
      self.eventStreamExpirationTime, forKey: .eventStreamExpirationTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.EventStream"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
