// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Specifies the Event-driven transfer options. Event-driven transfers listen to
/// an event stream to transfer updated files.
public struct EventStream: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Specifies a unique name of the resource such as AWS SQS
  /// ARN in the form 'arn:aws:sqs:region:account_id:queue_name',
  /// or Pub/Sub subscription resource name in the form
  /// 'projects/{project}/subscriptions/{sub}'.
  public var name: Swift.String = Swift.String()

  /// Specifies the date and time that Storage Transfer Service starts
  /// listening for events from this stream. If no start time is specified or
  /// start time is in the past, Storage Transfer Service starts listening
  /// immediately.
  public var eventStreamStartTime: GoogleCloudWkt.Timestamp? = nil

  /// Specifies the data and time at which Storage Transfer Service stops
  /// listening for events from this stream. After this time, any transfers in
  /// progress will complete, but no new transfers are initiated.
  public var eventStreamExpirationTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `EventStream`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EventStream().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.EventStream"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
