// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// In a GcsData resource, an object's name is the Cloud Storage object's
/// name and its "last modification time" refers to the object's `updated`
/// property of Cloud Storage objects, which changes when the content or the
/// metadata of the object is updated.
public struct GcsData: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Cloud Storage bucket name. Must meet
  /// [Bucket Name Requirements](/storage/docs/naming#requirements).
  public var bucketName: Swift.String = Swift.String()

  /// Root path to transfer objects.
  ///
  /// Must be an empty string or full path name that ends with a '/'. This field
  /// is treated as an object prefix. As such, it should generally not begin with
  /// a '/'.
  ///
  /// The root path value must meet
  /// [Object Name Requirements](/storage/docs/naming#objectnames).
  public var path: Swift.String = Swift.String()

  /// Preview. Enables the transfer of managed folders between Cloud Storage
  /// buckets. Set this option on the gcs_data_source.
  ///
  /// If set to true:
  ///
  /// - Managed folders in the source bucket are transferred to the
  ///   destination bucket.
  /// - Managed folders in the destination bucket are overwritten. Other
  ///   OVERWRITE options are not supported.
  ///
  /// See
  /// [Transfer Cloud Storage managed
  /// folders](/storage-transfer/docs/managed-folders).
  public var managedFolderTransferEnabled: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `GcsData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcsData().with { $0.bucketName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.GcsData"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
