// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An HttpData resource specifies a list of objects on the web to be
///  transferred over HTTP.  The information of the objects to be transferred is
///  contained in a file referenced by a URL. The first line in the file must be
///  `"TsvHttpData-1.0"`, which specifies the format of the file.  Subsequent
///  lines specify the information of the list of objects, one object per list
///  entry. Each entry has the following tab-delimited fields:
///
///  * **HTTP URL** — The location of the object.
///
///  * **Length** — The size of the object in bytes.
///
///  * **MD5** — The base64-encoded MD5 hash of the object.
///
///  For an example of a valid TSV file, see
///  [Transferring data from
///  URLs](https://cloud.google.com/storage-transfer/docs/create-url-list).
///
///  When transferring data based on a URL list, keep the following in mind:
///
/// * When an object located at `http(s)://hostname:port/<URL-path>` is
///  transferred to a data sink, the name of the object at the data sink is
/// `<hostname>/<URL-path>`.
///
/// * If the specified size of an object does not match the actual size of the
///  object fetched, the object is not transferred.
///
/// * If the specified MD5 does not match the MD5 computed from the transferred
///  bytes, the object transfer fails.
///
/// * Ensure that each URL you specify is publicly accessible. For
///  example, in Cloud Storage you can
///  [share an object publicly]
///  (/storage/docs/cloud-console#_sharingdata) and get a link to it.
///
/// * Storage Transfer Service obeys `robots.txt` rules and requires the source
///  HTTP server to support `Range` requests and to return a `Content-Length`
///  header in each response.
///
/// * [ObjectConditions][google.storagetransfer.v1.ObjectConditions] have no
/// effect when filtering objects to transfer.
///
/// [google.storagetransfer.v1.ObjectConditions]: <doc:ObjectConditions>
public struct HttpData: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The URL that points to the file that stores the object list
  /// entries. This file must allow public access. The URL is either an
  /// HTTP/HTTPS address (e.g. `https://example.com/urllist.tsv`) or a Cloud
  /// Storage path (e.g. `gs://my-bucket/urllist.tsv`).
  public var listUrl: Swift.String = Swift.String()

  /// Initialize a new instance of `HttpData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HttpData().with { $0.listUrl = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.HttpData"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
