// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// `projectId`, `jobNames`, and `jobStatuses` are query parameters that can
/// be specified when listing transfer jobs.
public struct ListTransferJobsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. A list of query parameters specified as JSON text in the form of:
  ///
  /// ```
  /// {
  ///   "projectId":"my_project_id",
  ///   "jobNames":["jobid1","jobid2",...],
  ///   "jobStatuses":["status1","status2",...],
  ///   "dataBackend":"QUERY_REPLICATION_CONFIGS",
  ///   "sourceBucket":"source-bucket-name",
  ///   "sinkBucket":"sink-bucket-name",
  /// }
  /// ```
  ///
  /// The JSON formatting in the example is for display only; provide the
  /// query parameters without spaces or line breaks.
  ///
  /// * `projectId` is required.
  /// * Since `jobNames` and `jobStatuses` support multiple values, their values
  ///   must be specified with array notation. `jobNames` and `jobStatuses` are
  ///   optional. Valid values are case-insensitive:
  ///     * [ENABLED][google.storagetransfer.v1.TransferJob.Status.ENABLED]
  ///     * [DISABLED][google.storagetransfer.v1.TransferJob.Status.DISABLED]
  ///     * [DELETED][google.storagetransfer.v1.TransferJob.Status.DELETED]
  /// * Specify `"dataBackend":"QUERY_REPLICATION_CONFIGS"` to return a list of
  ///   cross-bucket replication jobs.
  /// * Limit the results to jobs from a particular bucket with `sourceBucket`
  ///   and/or to a particular bucket with `sinkBucket`.
  ///
  /// [google.storagetransfer.v1.TransferJob.Status.DELETED]: <doc:TransferJob/Status/deleted>
  /// [google.storagetransfer.v1.TransferJob.Status.DISABLED]: <doc:TransferJob/Status/disabled>
  /// [google.storagetransfer.v1.TransferJob.Status.ENABLED]: <doc:TransferJob/Status/enabled>
  public var filter: Swift.String = Swift.String()

  /// The list page size. The max allowed value is 256.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The list page token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListTransferJobsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListTransferJobsRequest().with { $0.filter = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.storagetransfer.v1.ListTransferJobsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
