// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The request passed to ListAgentPools.
public struct ListAgentPoolsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The ID of the Google Cloud project that owns the job.
  public var projectId: Swift.String = Swift.String()

  /// An optional list of query parameters specified as JSON text in the
  /// form of:
  ///
  /// `{"agentPoolNames":["agentpool1","agentpool2",...]}`
  ///
  /// Since `agentPoolNames` support multiple values, its values must be
  /// specified with array notation. When the filter is either empty or not
  /// provided, the list returns all agent pools for the project.
  public var filter: Swift.String = Swift.String()

  /// The list page size. The max allowed value is `256`.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The list page token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListAgentPoolsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListAgentPoolsRequest().with { $0.projectId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.ListAgentPoolsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
