// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Specifies the metadata options for running a transfer.
public struct MetadataOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Specifies how symlinks should be handled by the transfer. By default,
  /// symlinks are not preserved. Only applicable to transfers involving
  /// POSIX file systems, and ignored for other transfers.
  public var symlink: MetadataOptions.Symlink = MetadataOptions.Symlink()

  /// Specifies how each file's mode attribute should be handled by the transfer.
  /// By default, mode is not preserved. Only applicable to transfers involving
  /// POSIX file systems, and ignored for other transfers.
  public var mode: MetadataOptions.Mode = MetadataOptions.Mode()

  /// Specifies how each file's POSIX group ID (GID) attribute should be handled
  /// by the transfer. By default, GID is not preserved. Only applicable to
  /// transfers involving POSIX file systems, and ignored for other transfers.
  public var gid: MetadataOptions.GID = MetadataOptions.GID()

  /// Specifies how each file's POSIX user ID (UID) attribute should be handled
  /// by the transfer. By default, UID is not preserved. Only applicable to
  /// transfers involving POSIX file systems, and ignored for other transfers.
  public var uid: MetadataOptions.UID = MetadataOptions.UID()

  /// Specifies how each object's ACLs should be preserved for transfers between
  /// Google Cloud Storage buckets. If unspecified, the default behavior is the
  /// same as ACL_DESTINATION_BUCKET_DEFAULT.
  public var acl: MetadataOptions.Acl = MetadataOptions.Acl()

  /// Specifies the storage class to set on objects being transferred to Google
  /// Cloud Storage buckets.  If unspecified, the default behavior is the same as
  /// [STORAGE_CLASS_DESTINATION_BUCKET_DEFAULT][google.storagetransfer.v1.MetadataOptions.StorageClass.STORAGE_CLASS_DESTINATION_BUCKET_DEFAULT].
  ///
  /// [google.storagetransfer.v1.MetadataOptions.StorageClass.STORAGE_CLASS_DESTINATION_BUCKET_DEFAULT]: <doc:MetadataOptions/StorageClass/destinationBucketDefault>
  public var storageClass: MetadataOptions.StorageClass = MetadataOptions.StorageClass()

  /// Specifies how each object's temporary hold status should be preserved for
  /// transfers between Google Cloud Storage buckets.  If unspecified, the
  /// default behavior is the same as
  /// [TEMPORARY_HOLD_PRESERVE][google.storagetransfer.v1.MetadataOptions.TemporaryHold.TEMPORARY_HOLD_PRESERVE].
  ///
  /// [google.storagetransfer.v1.MetadataOptions.TemporaryHold.TEMPORARY_HOLD_PRESERVE]: <doc:MetadataOptions/TemporaryHold/preserve>
  public var temporaryHold: MetadataOptions.TemporaryHold = MetadataOptions.TemporaryHold()

  /// Specifies how each object's Cloud KMS customer-managed encryption key
  /// (CMEK) is preserved for transfers between Google Cloud Storage buckets.  If
  /// unspecified, the default behavior is the same as
  /// [KMS_KEY_DESTINATION_BUCKET_DEFAULT][google.storagetransfer.v1.MetadataOptions.KmsKey.KMS_KEY_DESTINATION_BUCKET_DEFAULT].
  ///
  /// [google.storagetransfer.v1.MetadataOptions.KmsKey.KMS_KEY_DESTINATION_BUCKET_DEFAULT]: <doc:MetadataOptions/KmsKey/destinationBucketDefault>
  public var kmsKey: MetadataOptions.KmsKey = MetadataOptions.KmsKey()

  /// Specifies how each object's `timeCreated` metadata is preserved for
  /// transfers. If unspecified, the default behavior is the same as
  /// [TIME_CREATED_SKIP][google.storagetransfer.v1.MetadataOptions.TimeCreated.TIME_CREATED_SKIP].
  /// This behavior is supported for transfers to Cloud Storage buckets from
  /// Cloud Storage, Amazon S3, S3-compatible storage, and Azure sources.
  ///
  /// [google.storagetransfer.v1.MetadataOptions.TimeCreated.TIME_CREATED_SKIP]: <doc:MetadataOptions/TimeCreated/skip>
  public var timeCreated: MetadataOptions.TimeCreated = MetadataOptions.TimeCreated()

  /// Initialize a new instance of `MetadataOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MetadataOptions().with { $0.symlink = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Whether symlinks should be skipped or preserved during a transfer job.
  public enum Symlink: Codable, Equatable, Sendable {
    /// Symlink behavior is unspecified.
    case unspecified
    /// Do not preserve symlinks during a transfer job.
    case skip
    /// Preserve symlinks during a transfer job.
    case preserve
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .skip: return 1
      case .preserve: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "SYMLINK_UNSPECIFIED"
      case .skip: return "SYMLINK_SKIP"
      case .preserve: return "SYMLINK_PRESERVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "SYMLINK_UNSPECIFIED": self = .unspecified
      case "SYMLINK_SKIP": self = .skip
      case "SYMLINK_PRESERVE": self = .preserve
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .skip
      case 2: self = .preserve
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .skip: return try container.encode(1)
      case .preserve: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Options for handling file mode attribute.
  public enum Mode: Codable, Equatable, Sendable {
    /// Mode behavior is unspecified.
    case unspecified
    /// Do not preserve mode during a transfer job.
    case skip
    /// Preserve mode during a transfer job.
    case preserve
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .skip: return 1
      case .preserve: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "MODE_UNSPECIFIED"
      case .skip: return "MODE_SKIP"
      case .preserve: return "MODE_PRESERVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "MODE_UNSPECIFIED": self = .unspecified
      case "MODE_SKIP": self = .skip
      case "MODE_PRESERVE": self = .preserve
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .skip
      case 2: self = .preserve
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .skip: return try container.encode(1)
      case .preserve: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Options for handling file GID attribute.
  public enum GID: Codable, Equatable, Sendable {
    /// GID behavior is unspecified.
    case unspecified
    /// Do not preserve GID during a transfer job.
    case skip
    /// Preserve GID during a transfer job.
    case number
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .skip: return 1
      case .number: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "GID_UNSPECIFIED"
      case .skip: return "GID_SKIP"
      case .number: return "GID_NUMBER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "GID_UNSPECIFIED": self = .unspecified
      case "GID_SKIP": self = .skip
      case "GID_NUMBER": self = .number
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .skip
      case 2: self = .number
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .skip: return try container.encode(1)
      case .number: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Options for handling file UID attribute.
  public enum UID: Codable, Equatable, Sendable {
    /// UID behavior is unspecified.
    case unspecified
    /// Do not preserve UID during a transfer job.
    case skip
    /// Preserve UID during a transfer job.
    case number
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .skip: return 1
      case .number: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "UID_UNSPECIFIED"
      case .skip: return "UID_SKIP"
      case .number: return "UID_NUMBER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "UID_UNSPECIFIED": self = .unspecified
      case "UID_SKIP": self = .skip
      case "UID_NUMBER": self = .number
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .skip
      case 2: self = .number
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .skip: return try container.encode(1)
      case .number: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Options for handling Cloud Storage object ACLs.
  public enum Acl: Codable, Equatable, Sendable {
    /// ACL behavior is unspecified.
    case unspecified
    /// Use the destination bucket's default object ACLS, if applicable.
    case destinationBucketDefault
    /// Preserve the object's original ACLs. This requires the service account
    /// to have `storage.objects.getIamPolicy` permission for the source object.
    /// [Uniform bucket-level
    /// access](https://cloud.google.com/storage/docs/uniform-bucket-level-access)
    /// must not be enabled on either the source or destination buckets.
    case preserve
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .destinationBucketDefault: return 1
      case .preserve: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "ACL_UNSPECIFIED"
      case .destinationBucketDefault: return "ACL_DESTINATION_BUCKET_DEFAULT"
      case .preserve: return "ACL_PRESERVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "ACL_UNSPECIFIED": self = .unspecified
      case "ACL_DESTINATION_BUCKET_DEFAULT": self = .destinationBucketDefault
      case "ACL_PRESERVE": self = .preserve
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .destinationBucketDefault
      case 2: self = .preserve
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .destinationBucketDefault: return try container.encode(1)
      case .preserve: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Options for handling Google Cloud Storage object storage class.
  public enum StorageClass: Codable, Equatable, Sendable {
    /// Storage class behavior is unspecified.
    case unspecified
    /// Use the destination bucket's default storage class.
    case destinationBucketDefault
    /// Preserve the object's original storage class. This is only supported for
    /// transfers from Google Cloud Storage buckets. REGIONAL and MULTI_REGIONAL
    /// storage classes will be mapped to STANDARD to ensure they can be written
    /// to the destination bucket.
    case preserve
    /// Set the storage class to STANDARD.
    case standard
    /// Set the storage class to NEARLINE.
    case nearline
    /// Set the storage class to COLDLINE.
    case coldline
    /// Set the storage class to ARCHIVE.
    case archive
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .destinationBucketDefault: return 1
      case .preserve: return 2
      case .standard: return 3
      case .nearline: return 4
      case .coldline: return 5
      case .archive: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STORAGE_CLASS_UNSPECIFIED"
      case .destinationBucketDefault: return "STORAGE_CLASS_DESTINATION_BUCKET_DEFAULT"
      case .preserve: return "STORAGE_CLASS_PRESERVE"
      case .standard: return "STORAGE_CLASS_STANDARD"
      case .nearline: return "STORAGE_CLASS_NEARLINE"
      case .coldline: return "STORAGE_CLASS_COLDLINE"
      case .archive: return "STORAGE_CLASS_ARCHIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STORAGE_CLASS_UNSPECIFIED": self = .unspecified
      case "STORAGE_CLASS_DESTINATION_BUCKET_DEFAULT": self = .destinationBucketDefault
      case "STORAGE_CLASS_PRESERVE": self = .preserve
      case "STORAGE_CLASS_STANDARD": self = .standard
      case "STORAGE_CLASS_NEARLINE": self = .nearline
      case "STORAGE_CLASS_COLDLINE": self = .coldline
      case "STORAGE_CLASS_ARCHIVE": self = .archive
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .destinationBucketDefault
      case 2: self = .preserve
      case 3: self = .standard
      case 4: self = .nearline
      case 5: self = .coldline
      case 6: self = .archive
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .destinationBucketDefault: return try container.encode(1)
      case .preserve: return try container.encode(2)
      case .standard: return try container.encode(3)
      case .nearline: return try container.encode(4)
      case .coldline: return try container.encode(5)
      case .archive: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Options for handling temporary holds for Google Cloud Storage objects.
  public enum TemporaryHold: Codable, Equatable, Sendable {
    /// Temporary hold behavior is unspecified.
    case unspecified
    /// Do not set a temporary hold on the destination object.
    case skip
    /// Preserve the object's original temporary hold status.
    case preserve
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .skip: return 1
      case .preserve: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "TEMPORARY_HOLD_UNSPECIFIED"
      case .skip: return "TEMPORARY_HOLD_SKIP"
      case .preserve: return "TEMPORARY_HOLD_PRESERVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "TEMPORARY_HOLD_UNSPECIFIED": self = .unspecified
      case "TEMPORARY_HOLD_SKIP": self = .skip
      case "TEMPORARY_HOLD_PRESERVE": self = .preserve
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .skip
      case 2: self = .preserve
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .skip: return try container.encode(1)
      case .preserve: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Options for handling the KmsKey setting for Google Cloud Storage objects.
  public enum KmsKey: Codable, Equatable, Sendable {
    /// KmsKey behavior is unspecified.
    case unspecified
    /// Use the destination bucket's default encryption settings.
    case destinationBucketDefault
    /// Preserve the object's original Cloud KMS customer-managed encryption key
    /// (CMEK) if present. Objects that do not use a Cloud KMS encryption key
    /// will be encrypted using the destination bucket's encryption settings.
    case preserve
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .destinationBucketDefault: return 1
      case .preserve: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "KMS_KEY_UNSPECIFIED"
      case .destinationBucketDefault: return "KMS_KEY_DESTINATION_BUCKET_DEFAULT"
      case .preserve: return "KMS_KEY_PRESERVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "KMS_KEY_UNSPECIFIED": self = .unspecified
      case "KMS_KEY_DESTINATION_BUCKET_DEFAULT": self = .destinationBucketDefault
      case "KMS_KEY_PRESERVE": self = .preserve
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .destinationBucketDefault
      case 2: self = .preserve
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .destinationBucketDefault: return try container.encode(1)
      case .preserve: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Options for handling `timeCreated` metadata for Google Cloud Storage
  /// objects.
  public enum TimeCreated: Codable, Equatable, Sendable {
    /// TimeCreated behavior is unspecified.
    case unspecified
    /// Do not preserve the `timeCreated` metadata from the source object.
    case skip
    /// Preserves the source object's `timeCreated` or `lastModified` metadata in
    /// the `customTime` field in the destination object.  Note that any value
    /// stored in the source object's `customTime` field will not be propagated
    /// to the destination object.
    case preserveAsCustomTime
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .skip: return 1
      case .preserveAsCustomTime: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "TIME_CREATED_UNSPECIFIED"
      case .skip: return "TIME_CREATED_SKIP"
      case .preserveAsCustomTime: return "TIME_CREATED_PRESERVE_AS_CUSTOM_TIME"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "TIME_CREATED_UNSPECIFIED": self = .unspecified
      case "TIME_CREATED_SKIP": self = .skip
      case "TIME_CREATED_PRESERVE_AS_CUSTOM_TIME": self = .preserveAsCustomTime
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .skip
      case 2: self = .preserveAsCustomTime
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .skip: return try container.encode(1)
      case .preserveAsCustomTime: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.storagetransfer.v1.MetadataOptions"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
