// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Specification to configure notifications published to Pub/Sub.
/// Notifications are published to the customer-provided topic using the
/// following `PubsubMessage.attributes`:
///
/// * `"eventType"`: one of the
/// [EventType][google.storagetransfer.v1.NotificationConfig.EventType] values
/// * `"payloadFormat"`: one of the
/// [PayloadFormat][google.storagetransfer.v1.NotificationConfig.PayloadFormat]
/// values
/// * `"projectId"`: the
/// [project_id][google.storagetransfer.v1.TransferOperation.project_id] of the
/// `TransferOperation`
/// * `"transferJobName"`: the
/// [transfer_job_name][google.storagetransfer.v1.TransferOperation.transfer_job_name]
/// of the `TransferOperation`
/// * `"transferOperationName"`: the
/// [name][google.storagetransfer.v1.TransferOperation.name] of the
/// `TransferOperation`
///
/// The `PubsubMessage.data` contains a
/// [TransferOperation][google.storagetransfer.v1.TransferOperation] resource
/// formatted according to the specified `PayloadFormat`.
///
/// [google.storagetransfer.v1.NotificationConfig.EventType]: <doc:NotificationConfig/EventType>
/// [google.storagetransfer.v1.NotificationConfig.PayloadFormat]: <doc:NotificationConfig/PayloadFormat>
/// [google.storagetransfer.v1.TransferOperation]: <doc:TransferOperation>
/// [google.storagetransfer.v1.TransferOperation.name]: <doc:TransferOperation/name>
/// [google.storagetransfer.v1.TransferOperation.project_id]: <doc:TransferOperation/projectId>
/// [google.storagetransfer.v1.TransferOperation.transfer_job_name]: <doc:TransferOperation/transferJobName>
public struct NotificationConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The `Topic.name` of the Pub/Sub topic to which to publish
  /// notifications. Must be of the format: `projects/{project}/topics/{topic}`.
  /// Not matching this format results in an
  /// [INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT] error.
  ///
  /// [google.rpc.Code.INVALID_ARGUMENT]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Code/invalidArgument
  public var pubsubTopic: Swift.String = Swift.String()

  /// Event types for which a notification is desired. If empty, send
  /// notifications for all event types.
  public var eventTypes: [NotificationConfig.EventType] = []

  /// Required. The desired format of the notification message payloads.
  public var payloadFormat: NotificationConfig.PayloadFormat = NotificationConfig.PayloadFormat()

  /// Initialize a new instance of `NotificationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NotificationConfig().with { $0.pubsubTopic = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Enum for specifying event types for which notifications are to be
  /// published.
  ///
  /// Additional event types may be added in the future. Clients should either
  /// safely ignore unrecognized event types or explicitly specify which event
  /// types they are prepared to accept.
  public enum EventType: Codable, Equatable, Sendable {
    /// Illegal value, to avoid allowing a default.
    case unspecified
    /// `TransferOperation` completed with status
    /// [SUCCESS][google.storagetransfer.v1.TransferOperation.Status.SUCCESS].
    ///
    /// [google.storagetransfer.v1.TransferOperation.Status.SUCCESS]: <doc:TransferOperation/Status/success>
    case transferOperationSuccess
    /// `TransferOperation` completed with status
    /// [FAILED][google.storagetransfer.v1.TransferOperation.Status.FAILED].
    ///
    /// [google.storagetransfer.v1.TransferOperation.Status.FAILED]: <doc:TransferOperation/Status/failed>
    case transferOperationFailed
    /// `TransferOperation` completed with status
    /// [ABORTED][google.storagetransfer.v1.TransferOperation.Status.ABORTED].
    ///
    /// [google.storagetransfer.v1.TransferOperation.Status.ABORTED]: <doc:TransferOperation/Status/aborted>
    case transferOperationAborted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .transferOperationSuccess: return 1
      case .transferOperationFailed: return 2
      case .transferOperationAborted: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EVENT_TYPE_UNSPECIFIED"
      case .transferOperationSuccess: return "TRANSFER_OPERATION_SUCCESS"
      case .transferOperationFailed: return "TRANSFER_OPERATION_FAILED"
      case .transferOperationAborted: return "TRANSFER_OPERATION_ABORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EventType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EVENT_TYPE_UNSPECIFIED": self = .unspecified
      case "TRANSFER_OPERATION_SUCCESS": self = .transferOperationSuccess
      case "TRANSFER_OPERATION_FAILED": self = .transferOperationFailed
      case "TRANSFER_OPERATION_ABORTED": self = .transferOperationAborted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EventType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .transferOperationSuccess
      case 2: self = .transferOperationFailed
      case 3: self = .transferOperationAborted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .transferOperationSuccess: return try container.encode(1)
      case .transferOperationFailed: return try container.encode(2)
      case .transferOperationAborted: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Enum for specifying the format of a notification message's payload.
  public enum PayloadFormat: Codable, Equatable, Sendable {
    /// Illegal value, to avoid allowing a default.
    case unspecified
    /// No payload is included with the notification.
    case `none`
    /// `TransferOperation` is [formatted as a JSON
    /// response](https://developers.google.com/protocol-buffers/docs/proto3#json),
    /// in application/json.
    case json
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`none`: return 1
      case .json: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PAYLOAD_FORMAT_UNSPECIFIED"
      case .`none`: return "NONE"
      case .json: return "JSON"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PayloadFormat/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PAYLOAD_FORMAT_UNSPECIFIED": self = .unspecified
      case "NONE": self = .`none`
      case "JSON": self = .json
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PayloadFormat/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`none`
      case 2: self = .json
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .`none`: return try container.encode(1)
      case .json: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.NotificationConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
