// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Specifies the configuration for a cross-bucket replication job. Cross-bucket
/// replication copies new or updated objects from a source Cloud Storage bucket
/// to a destination Cloud Storage bucket. Existing objects in the source bucket
/// are not copied by a new cross-bucket replication job.
public struct ReplicationSpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Object conditions that determine which objects are transferred. For
  /// replication jobs, only `include_prefixes` and `exclude_prefixes` are
  /// supported.
  public var objectConditions: ObjectConditions? = nil

  /// Specifies the metadata options to be applied during replication.
  /// Delete options are not supported. If a delete option is specified, the
  /// request fails with an [INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT]
  /// error.
  ///
  /// [google.rpc.Code.INVALID_ARGUMENT]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Code/invalidArgument
  public var transferOptions: TransferOptions? = nil

  /// The data source to be replicated.
  public var dataSource: OneOf_DataSource? = nil

  /// The destination for replicated objects.
  public var dataSink: OneOf_DataSink? = nil

  /// Initialize a new instance of `ReplicationSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReplicationSpec().with { $0.gcsDataSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case gcsDataSource = "gcsDataSource"
    case gcsDataSink = "gcsDataSink"
    case objectConditions = "objectConditions"
    case transferOptions = "transferOptions"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.objectConditions = try container.decodeIfPresent(
      ObjectConditions.self, forKey: .objectConditions)
    self.transferOptions = try container.decodeIfPresent(
      TransferOptions.self, forKey: .transferOptions)

    var dataSource: OneOf_DataSource? = nil
    let dataSourceCheckAndSet = {
      if dataSource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'dataSource'"))
      }
      dataSource = $0
    }
    if let gcsDataSource = try container.decodeIfPresent(GcsData?.self, forKey: .gcsDataSource) {
      try dataSourceCheckAndSet(.gcsDataSource(gcsDataSource))
    }
    self.dataSource = dataSource

    var dataSink: OneOf_DataSink? = nil
    let dataSinkCheckAndSet = {
      if dataSink != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'dataSink'"))
      }
      dataSink = $0
    }
    if let gcsDataSink = try container.decodeIfPresent(GcsData?.self, forKey: .gcsDataSink) {
      try dataSinkCheckAndSet(.gcsDataSink(gcsDataSink))
    }
    self.dataSink = dataSink
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.objectConditions, forKey: .objectConditions)
    try container.encode(self.transferOptions, forKey: .transferOptions)

    if let choice = self.dataSource {
      switch choice {
      case .gcsDataSource(let value):
        try container.encode(value, forKey: .gcsDataSource)
      }
    }

    if let choice = self.dataSink {
      switch choice {
      case .gcsDataSink(let value):
        try container.encode(value, forKey: .gcsDataSink)
      }
    }
  }

  /// The data source to be replicated.
  public enum OneOf_DataSource: Codable, Equatable, Sendable {
    /// The Cloud Storage bucket from which to replicate objects.
    indirect case gcsDataSource(GcsData?)
  }

  /// The destination for replicated objects.
  public enum OneOf_DataSink: Codable, Equatable, Sendable {
    /// The Cloud Storage bucket to which to replicate objects.
    indirect case gcsDataSink(GcsData?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.storagetransfer.v1.ReplicationSpec"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
