// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// S3CompatibleMetadata contains the metadata fields that apply to the basic
/// types of S3-compatible data providers.
public struct S3CompatibleMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Specifies the authentication and authorization method used by the storage
  /// service. When not specified, Transfer Service will attempt to determine
  /// right auth method to use.
  public var authMethod: S3CompatibleMetadata.AuthMethod = S3CompatibleMetadata.AuthMethod()

  /// Specifies the API request model used to call the storage service. When not
  /// specified, the default value of RequestModel
  /// REQUEST_MODEL_VIRTUAL_HOSTED_STYLE is used.
  public var requestModel: S3CompatibleMetadata.RequestModel = S3CompatibleMetadata.RequestModel()

  /// Specifies the network protocol of the agent. When not specified, the
  /// default value of NetworkProtocol NETWORK_PROTOCOL_HTTPS is used.
  public var `protocol`: S3CompatibleMetadata.NetworkProtocol =
    S3CompatibleMetadata.NetworkProtocol()

  /// The Listing API to use for discovering objects. When not specified,
  /// Transfer Service will attempt to determine the right API to use.
  public var listApi: S3CompatibleMetadata.ListApi = S3CompatibleMetadata.ListApi()

  /// Initialize a new instance of `S3CompatibleMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = S3CompatibleMetadata().with { $0.authMethod = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case authMethod = "authMethod"
    case requestModel = "requestModel"
    case `protocol` = "protocol"
    case listApi = "listApi"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.authMethod = try container.decode(
      S3CompatibleMetadata.AuthMethod.self, forKey: .authMethod)
    self.requestModel = try container.decode(
      S3CompatibleMetadata.RequestModel.self, forKey: .requestModel)
    self.`protocol` = try container.decode(
      S3CompatibleMetadata.NetworkProtocol.self, forKey: .`protocol`)
    self.listApi = try container.decode(S3CompatibleMetadata.ListApi.self, forKey: .listApi)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.authMethod, forKey: .authMethod)
    try container.encode(self.requestModel, forKey: .requestModel)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    try container.encode(self.listApi, forKey: .listApi)
  }

  /// The authentication and authorization method used by the storage service.
  public enum AuthMethod: Codable, Equatable, Sendable {
    /// AuthMethod is not specified.
    case unspecified
    /// Auth requests with AWS SigV4.
    case awsSignatureV4
    /// Auth requests with AWS SigV2.
    case awsSignatureV2
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .awsSignatureV4: return 1
      case .awsSignatureV2: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AUTH_METHOD_UNSPECIFIED"
      case .awsSignatureV4: return "AUTH_METHOD_AWS_SIGNATURE_V4"
      case .awsSignatureV2: return "AUTH_METHOD_AWS_SIGNATURE_V2"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AuthMethod/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AUTH_METHOD_UNSPECIFIED": self = .unspecified
      case "AUTH_METHOD_AWS_SIGNATURE_V4": self = .awsSignatureV4
      case "AUTH_METHOD_AWS_SIGNATURE_V2": self = .awsSignatureV2
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AuthMethod/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .awsSignatureV4
      case 2: self = .awsSignatureV2
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .awsSignatureV4: return try container.encode(1)
      case .awsSignatureV2: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The request model of the API.
  public enum RequestModel: Codable, Equatable, Sendable {
    /// RequestModel is not specified.
    case unspecified
    /// Perform requests using Virtual Hosted Style.
    /// Example: https://bucket-name.s3.region.amazonaws.com/key-name
    case virtualHostedStyle
    /// Perform requests using Path Style.
    /// Example: https://s3.region.amazonaws.com/bucket-name/key-name
    case pathStyle
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .virtualHostedStyle: return 1
      case .pathStyle: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "REQUEST_MODEL_UNSPECIFIED"
      case .virtualHostedStyle: return "REQUEST_MODEL_VIRTUAL_HOSTED_STYLE"
      case .pathStyle: return "REQUEST_MODEL_PATH_STYLE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RequestModel/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REQUEST_MODEL_UNSPECIFIED": self = .unspecified
      case "REQUEST_MODEL_VIRTUAL_HOSTED_STYLE": self = .virtualHostedStyle
      case "REQUEST_MODEL_PATH_STYLE": self = .pathStyle
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RequestModel/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .virtualHostedStyle
      case 2: self = .pathStyle
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .virtualHostedStyle: return try container.encode(1)
      case .pathStyle: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The agent network protocol to access the storage service.
  public enum NetworkProtocol: Codable, Equatable, Sendable {
    /// NetworkProtocol is not specified.
    case unspecified
    /// Perform requests using HTTPS.
    case https
    /// Not recommended: This sends data in clear-text. This is only
    /// appropriate within a closed network or for publicly available data.
    /// Perform requests using HTTP.
    case http
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .https: return 1
      case .http: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "NETWORK_PROTOCOL_UNSPECIFIED"
      case .https: return "NETWORK_PROTOCOL_HTTPS"
      case .http: return "NETWORK_PROTOCOL_HTTP"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NetworkProtocol/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "NETWORK_PROTOCOL_UNSPECIFIED": self = .unspecified
      case "NETWORK_PROTOCOL_HTTPS": self = .https
      case "NETWORK_PROTOCOL_HTTP": self = .http
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:NetworkProtocol/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .https
      case 2: self = .http
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .https: return try container.encode(1)
      case .http: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The Listing API to use for discovering objects.
  public enum ListApi: Codable, Equatable, Sendable {
    /// ListApi is not specified.
    case unspecified
    /// Perform listing using ListObjectsV2 API.
    case listObjectsV2
    /// Legacy ListObjects API.
    case listObjects
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .listObjectsV2: return 1
      case .listObjects: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "LIST_API_UNSPECIFIED"
      case .listObjectsV2: return "LIST_OBJECTS_V2"
      case .listObjects: return "LIST_OBJECTS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ListApi/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "LIST_API_UNSPECIFIED": self = .unspecified
      case "LIST_OBJECTS_V2": self = .listObjectsV2
      case "LIST_OBJECTS": self = .listObjects
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ListApi/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .listObjectsV2
      case 2: self = .listObjects
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .listObjectsV2: return try container.encode(1)
      case .listObjects: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.S3CompatibleMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
