// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// Transfers can be scheduled to recur or to run just once.
public struct Schedule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The start date of a transfer. Date boundaries are determined
  /// relative to UTC time. If `schedule_start_date` and
  /// [start_time_of_day][google.storagetransfer.v1.Schedule.start_time_of_day]
  /// are in the past relative to the job's creation time, the transfer starts
  /// the day after you schedule the transfer request.
  ///
  /// **Note:** When starting jobs at or near midnight UTC it is possible that
  /// a job starts later than expected. For example, if you send an outbound
  /// request on June 1 one millisecond prior to midnight UTC and the Storage
  /// Transfer Service server receives the request on June 2, then it creates
  /// a TransferJob with `schedule_start_date` set to June 2 and a
  /// `start_time_of_day` set to midnight UTC. The first scheduled
  /// [TransferOperation][google.storagetransfer.v1.TransferOperation] takes
  /// place on June 3 at midnight UTC.
  ///
  /// [google.storagetransfer.v1.Schedule.start_time_of_day]: <doc:Schedule/startTimeOfDay>
  /// [google.storagetransfer.v1.TransferOperation]: <doc:TransferOperation>
  public var scheduleStartDate: GoogleType.Date? = nil

  /// The last day a transfer runs. Date boundaries are determined relative to
  /// UTC time. A job runs once per 24 hours within the following guidelines:
  ///
  /// *   If `schedule_end_date` and
  /// [schedule_start_date][google.storagetransfer.v1.Schedule.schedule_start_date]
  /// are the same and in
  ///     the future relative to UTC, the transfer is executed only one time.
  /// *   If `schedule_end_date` is later than `schedule_start_date`  and
  ///     `schedule_end_date` is in the future relative to UTC, the job runs each
  ///     day at
  ///     [start_time_of_day][google.storagetransfer.v1.Schedule.start_time_of_day]
  ///     through `schedule_end_date`.
  ///
  /// [google.storagetransfer.v1.Schedule.schedule_start_date]: <doc:Schedule/scheduleStartDate>
  /// [google.storagetransfer.v1.Schedule.start_time_of_day]: <doc:Schedule/startTimeOfDay>
  public var scheduleEndDate: GoogleType.Date? = nil

  /// The time in UTC that a transfer job is scheduled to run. Transfers may
  /// start later than this time.
  ///
  /// If `start_time_of_day` is not specified:
  ///
  /// *   One-time transfers run immediately.
  /// *   Recurring transfers run immediately, and each day at midnight UTC,
  ///     through
  ///     [schedule_end_date][google.storagetransfer.v1.Schedule.schedule_end_date].
  ///
  /// If `start_time_of_day` is specified:
  ///
  /// *   One-time transfers run at the specified time.
  /// *   Recurring transfers run at the specified time each day, through
  ///     `schedule_end_date`.
  ///
  /// [google.storagetransfer.v1.Schedule.schedule_end_date]: <doc:Schedule/scheduleEndDate>
  public var startTimeOfDay: GoogleType.TimeOfDay? = nil

  /// The time in UTC that no further transfer operations are scheduled. Combined
  /// with
  /// [schedule_end_date][google.storagetransfer.v1.Schedule.schedule_end_date],
  /// `end_time_of_day` specifies the end date and time for starting new transfer
  /// operations. This field must be greater than or equal to the timestamp
  /// corresponding to the combination of
  /// [schedule_start_date][google.storagetransfer.v1.Schedule.schedule_start_date]
  /// and
  /// [start_time_of_day][google.storagetransfer.v1.Schedule.start_time_of_day],
  /// and is subject to the following:
  ///
  /// *   If `end_time_of_day` is not set and `schedule_end_date` is set, then
  ///     a default value of `23:59:59` is used for `end_time_of_day`.
  ///
  /// *   If `end_time_of_day` is set and `schedule_end_date` is not set, then
  ///     [INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT] is returned.
  ///
  /// [google.rpc.Code.INVALID_ARGUMENT]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Code/invalidArgument
  /// [google.storagetransfer.v1.Schedule.schedule_end_date]: <doc:Schedule/scheduleEndDate>
  /// [google.storagetransfer.v1.Schedule.schedule_start_date]: <doc:Schedule/scheduleStartDate>
  /// [google.storagetransfer.v1.Schedule.start_time_of_day]: <doc:Schedule/startTimeOfDay>
  public var endTimeOfDay: GoogleType.TimeOfDay? = nil

  /// Interval between the start of each scheduled TransferOperation. If
  /// unspecified, the default value is 24 hours. This value may not be less than
  /// 1 hour.
  public var repeatInterval: GoogleCloudWkt.Duration? = nil

  /// Initialize a new instance of `Schedule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Schedule().with { $0.scheduleStartDate = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.Schedule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
