// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class StorageTransferServiceRetry: StorageTransferServiceStub {
    let inner: any StorageTransferServiceStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any StorageTransferServiceStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func getGoogleServiceAccount(
      request: GetGoogleServiceAccountRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.GoogleServiceAccount {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetGoogleServiceAccountRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleStorageTransferV1.GoogleServiceAccount
          in
          return try await self.inner.getGoogleServiceAccount(request: r, options: o)
        })
    }

    public func createTransferJob(
      request: CreateTransferJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.TransferJob {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateTransferJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleStorageTransferV1.TransferJob
          in
          return try await self.inner.createTransferJob(request: r, options: o)
        })
    }

    public func updateTransferJob(
      request: UpdateTransferJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.TransferJob {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateTransferJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleStorageTransferV1.TransferJob
          in
          return try await self.inner.updateTransferJob(request: r, options: o)
        })
    }

    public func getTransferJob(
      request: GetTransferJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.TransferJob {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetTransferJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleStorageTransferV1.TransferJob
          in
          return try await self.inner.getTransferJob(request: r, options: o)
        })
    }

    public func listTransferJobs(
      request: ListTransferJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.ListTransferJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTransferJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleStorageTransferV1.ListTransferJobsResponse
          in
          return try await self.inner.listTransferJobs(request: r, options: o)
        })
    }

    public func pauseTransferOperation(
      request: PauseTransferOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: PauseTransferOperationRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.pauseTransferOperation(request: r, options: o)
        })
    }

    public func resumeTransferOperation(
      request: ResumeTransferOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ResumeTransferOperationRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.resumeTransferOperation(request: r, options: o)
        })
    }

    public func runTransferJob(
      request: RunTransferJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RunTransferJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.runTransferJob(request: r, options: o)
        })
    }

    public func deleteTransferJob(
      request: DeleteTransferJobRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteTransferJobRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTransferJob(request: r, options: o)
        })
    }

    public func createAgentPool(
      request: CreateAgentPoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.AgentPool {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateAgentPoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleStorageTransferV1.AgentPool
          in
          return try await self.inner.createAgentPool(request: r, options: o)
        })
    }

    public func updateAgentPool(
      request: UpdateAgentPoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.AgentPool {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateAgentPoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleStorageTransferV1.AgentPool
          in
          return try await self.inner.updateAgentPool(request: r, options: o)
        })
    }

    public func getAgentPool(
      request: GetAgentPoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.AgentPool {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAgentPoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleStorageTransferV1.AgentPool
          in
          return try await self.inner.getAgentPool(request: r, options: o)
        })
    }

    public func listAgentPools(
      request: ListAgentPoolsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.ListAgentPoolsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAgentPoolsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleStorageTransferV1.ListAgentPoolsResponse
          in
          return try await self.inner.listAgentPools(request: r, options: o)
        })
    }

    public func deleteAgentPool(
      request: DeleteAgentPoolRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteAgentPoolRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAgentPool(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
