// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol StorageTransferServiceStub: Sendable {
    func getGoogleServiceAccount(
      request: GetGoogleServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.GoogleServiceAccount

    func createTransferJob(
      request: CreateTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.TransferJob

    func updateTransferJob(
      request: UpdateTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.TransferJob

    func getTransferJob(
      request: GetTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.TransferJob

    func listTransferJobs(
      request: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.ListTransferJobsResponse

    func pauseTransferOperation(
      request: PauseTransferOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func resumeTransferOperation(
      request: ResumeTransferOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func runTransferJob(
      request: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteTransferJob(
      request: DeleteTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createAgentPool(
      request: CreateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.AgentPool

    func updateAgentPool(
      request: UpdateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.AgentPool

    func getAgentPool(
      request: GetAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.AgentPool

    func listAgentPools(
      request: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.ListAgentPoolsResponse

    func deleteAgentPool(
      request: DeleteAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
