// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Storage Transfer Service and its protos.
/// Transfers data between between Google Cloud Storage buckets or from a data
/// source external to Google to a Cloud Storage bucket.
///
/// @Snippet(path: "StorageTransferServiceQuickstart")
public class StorageTransferServiceClient: Clients.StorageTransferServiceProtocol {
  let inner: any Clients.StorageTransferServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `StorageTransferServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.StorageTransferServiceStub = try Clients.StorageTransferServiceTransport(
      options)
    inner = Clients.StorageTransferServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.StorageTransferServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Returns the Google service account that is used by Storage Transfer
  /// Service to access buckets in the project where transfers
  /// run or in other projects. Each Google service account is associated
  /// with one Google Cloud project. Users
  /// should add this service account to the Google Cloud Storage bucket
  /// ACLs to grant access to Storage Transfer Service. This service
  /// account is created and owned by Storage Transfer Service and can
  /// only be used by Storage Transfer Service.
  ///
  /// @Snippet(path: "StorageTransferService_GetGoogleServiceAccount")
  public func getGoogleServiceAccount(
    request: GetGoogleServiceAccountRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.GoogleServiceAccount {
    try await self.inner.getGoogleServiceAccount(request: request, options: options)
  }

  /// Creates a transfer job that runs periodically.
  ///
  /// @Snippet(path: "StorageTransferService_CreateTransferJob")
  public func createTransferJob(
    request: CreateTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.TransferJob {
    try await self.inner.createTransferJob(request: request, options: options)
  }

  /// Updates a transfer job. Updating a job's transfer spec does not affect
  /// transfer operations that are running already.
  ///
  /// **Note:** The job's [status][google.storagetransfer.v1.TransferJob.status]
  /// field can be modified using this RPC (for example, to set a job's status to
  /// [DELETED][google.storagetransfer.v1.TransferJob.Status.DELETED],
  /// [DISABLED][google.storagetransfer.v1.TransferJob.Status.DISABLED], or
  /// [ENABLED][google.storagetransfer.v1.TransferJob.Status.ENABLED]).
  ///
  /// [google.storagetransfer.v1.TransferJob.Status.DELETED]: <doc:TransferJob/Status/deleted>
  /// [google.storagetransfer.v1.TransferJob.Status.DISABLED]: <doc:TransferJob/Status/disabled>
  /// [google.storagetransfer.v1.TransferJob.Status.ENABLED]: <doc:TransferJob/Status/enabled>
  /// [google.storagetransfer.v1.TransferJob.status]: <doc:TransferJob/status>
  ///
  /// @Snippet(path: "StorageTransferService_UpdateTransferJob")
  public func updateTransferJob(
    request: UpdateTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.TransferJob {
    try await self.inner.updateTransferJob(request: request, options: options)
  }

  /// Gets a transfer job.
  ///
  /// @Snippet(path: "StorageTransferService_GetTransferJob")
  public func getTransferJob(
    request: GetTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.TransferJob {
    try await self.inner.getTransferJob(request: request, options: options)
  }

  /// Lists transfer jobs.
  ///
  /// @Snippet(path: "StorageTransferService_ListTransferJobs")
  public func listTransferJobs(
    request: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.ListTransferJobsResponse {
    try await self.inner.listTransferJobs(request: request, options: options)
  }

  /// Lists transfer jobs.
  ///
  /// @Snippet(path: "StorageTransferService_ListTransferJobs")
  public func listTransferJobs(
    byItem: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TransferJob, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleStorageTransferV1.ListTransferJobsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listTransferJobs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Pauses a transfer operation.
  ///
  /// @Snippet(path: "StorageTransferService_PauseTransferOperation")
  public func pauseTransferOperation(
    request: PauseTransferOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.pauseTransferOperation(request: request, options: options)
  }

  /// Resumes a transfer operation that is paused.
  ///
  /// @Snippet(path: "StorageTransferService_ResumeTransferOperation")
  public func resumeTransferOperation(
    request: ResumeTransferOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.resumeTransferOperation(request: request, options: options)
  }

  /// Starts a new operation for the specified transfer job.
  /// A `TransferJob` has a maximum of one active `TransferOperation`. If this
  /// method is called while a `TransferOperation` is active, an error is
  /// returned.
  ///
  /// @Snippet(path: "StorageTransferService_RunTransferJob")
  public func runTransferJob(
    request: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.runTransferJob(request: request, options: options)
  }

  /// Starts a new operation for the specified transfer job.
  /// A `TransferJob` has a maximum of one active `TransferOperation`. If this
  /// method is called while a `TransferOperation` is active, an error is
  /// returned.
  ///
  /// @Snippet(path: "StorageTransferService_RunTransferJob")
  public func runTransferJob(
    withPolling: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.runTransferJob(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a transfer job. Deleting a transfer job sets its status to
  /// [DELETED][google.storagetransfer.v1.TransferJob.Status.DELETED].
  ///
  /// [google.storagetransfer.v1.TransferJob.Status.DELETED]: <doc:TransferJob/Status/deleted>
  ///
  /// @Snippet(path: "StorageTransferService_DeleteTransferJob")
  public func deleteTransferJob(
    request: DeleteTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteTransferJob(request: request, options: options)
  }

  /// Creates an agent pool resource.
  ///
  /// @Snippet(path: "StorageTransferService_CreateAgentPool")
  public func createAgentPool(
    request: CreateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.AgentPool {
    try await self.inner.createAgentPool(request: request, options: options)
  }

  /// Updates an existing agent pool resource.
  ///
  /// @Snippet(path: "StorageTransferService_UpdateAgentPool")
  public func updateAgentPool(
    request: UpdateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.AgentPool {
    try await self.inner.updateAgentPool(request: request, options: options)
  }

  /// Gets an agent pool.
  ///
  /// @Snippet(path: "StorageTransferService_GetAgentPool")
  public func getAgentPool(
    request: GetAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.AgentPool {
    try await self.inner.getAgentPool(request: request, options: options)
  }

  /// Lists agent pools.
  ///
  /// @Snippet(path: "StorageTransferService_ListAgentPools")
  public func listAgentPools(
    request: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.ListAgentPoolsResponse {
    try await self.inner.listAgentPools(request: request, options: options)
  }

  /// Lists agent pools.
  ///
  /// @Snippet(path: "StorageTransferService_ListAgentPools")
  public func listAgentPools(
    byItem: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AgentPool, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleStorageTransferV1.ListAgentPoolsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAgentPools(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Deletes an agent pool.
  ///
  /// @Snippet(path: "StorageTransferService_DeleteAgentPool")
  public func deleteAgentPool(
    request: DeleteAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteAgentPool(request: request, options: options)
  }

  /// Lists transfer operations. Operations are ordered by their creation
  /// time in reverse chronological order.
  ///
  /// @Snippet(path: "StorageTransferService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Lists transfer operations. Operations are ordered by their creation
  /// time in reverse chronological order.
  ///
  /// @Snippet(path: "StorageTransferService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "StorageTransferService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Cancels a transfer. Use
  /// the [transferOperations.get][google.longrunning.Operations.GetOperation]
  /// method to check if the cancellation succeeded or if the operation
  /// completed despite the `cancel` request.
  ///
  /// When you cancel an operation, the currently running transfer is
  /// interrupted.  For recurring transfer jobs, the next instance of the
  /// transfer job will still run.  For example, if your job is configured
  /// to run every day at 1pm and you cancel Monday's operation at 1:05pm,
  /// Monday's transfer
  /// will stop. However, a transfer job will still be attempted on Tuesday.
  ///
  /// This applies only to currently running operations. If an operation is
  /// not currently running, `cancel` does nothing.
  ///
  /// <aside class="caution">
  /// <b>Caution:</b> Canceling a transfer job can leave your data in an
  /// unknown state. We recommend that you restore the state at both the
  /// destination and the source after the `cancel` request completes so
  /// that your data is in a consistent state. </aside>
  ///
  /// When you cancel a job, the next job computes a delta of files and may
  /// repair any inconsistent state. For instance, if you run a job every
  /// day, and today's job found 10 new files and transferred five files
  /// before you canceled the job, tomorrow's transfer operation will
  /// compute a new delta with the five files that were not copied today
  /// plus any new files discovered tomorrow.
  ///
  /// @Snippet(path: "StorageTransferService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `StorageTransferServiceClient`.
  ///
  /// To mock `StorageTransferServiceClient` change your functions to receive
  /// `some StorageTransferServiceProtocol` or `any StorageTransferServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol StorageTransferServiceProtocol {
    /// See `StorageTransferServiceClient.getGoogleServiceAccount`.
    func getGoogleServiceAccount(request: GetGoogleServiceAccountRequest) async throws
      -> GoogleStorageTransferV1.GoogleServiceAccount

    /// See `StorageTransferServiceClient.createTransferJob`.
    func createTransferJob(request: CreateTransferJobRequest) async throws
      -> GoogleStorageTransferV1.TransferJob

    /// See `StorageTransferServiceClient.updateTransferJob`.
    func updateTransferJob(request: UpdateTransferJobRequest) async throws
      -> GoogleStorageTransferV1.TransferJob

    /// See `StorageTransferServiceClient.getTransferJob`.
    func getTransferJob(request: GetTransferJobRequest) async throws
      -> GoogleStorageTransferV1.TransferJob

    /// See `StorageTransferServiceClient.listTransferJobs`.
    func listTransferJobs(request: ListTransferJobsRequest) async throws
      -> GoogleStorageTransferV1.ListTransferJobsResponse

    /// See `StorageTransferServiceClient.listTransferJobs`.
    func listTransferJobs(
      byItem: ListTransferJobsRequest
    ) throws -> any AsyncSequence<TransferJob, Swift.Error>

    /// See `StorageTransferServiceClient.pauseTransferOperation`.
    func pauseTransferOperation(request: PauseTransferOperationRequest) async throws

    /// See `StorageTransferServiceClient.resumeTransferOperation`.
    func resumeTransferOperation(request: ResumeTransferOperationRequest) async throws

    /// See `StorageTransferServiceClient.runTransferJob`.
    func runTransferJob(request: RunTransferJobRequest) async throws -> GoogleLongRunning.Operation

    /// See `StorageTransferServiceClient.runTransferJob`.
    func runTransferJob(withPolling: RunTransferJobRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `StorageTransferServiceClient.deleteTransferJob`.
    func deleteTransferJob(request: DeleteTransferJobRequest) async throws

    /// See `StorageTransferServiceClient.createAgentPool`.
    func createAgentPool(request: CreateAgentPoolRequest) async throws
      -> GoogleStorageTransferV1.AgentPool

    /// See `StorageTransferServiceClient.createAgentPool`.
    func createAgentPool(
      projectId: Swift.String,
      agentPool: AgentPool?,
      agentPoolId: Swift.String,
    ) async throws -> GoogleStorageTransferV1.AgentPool

    /// See `StorageTransferServiceClient.updateAgentPool`.
    func updateAgentPool(request: UpdateAgentPoolRequest) async throws
      -> GoogleStorageTransferV1.AgentPool

    /// See `StorageTransferServiceClient.updateAgentPool`.
    func updateAgentPool(
      agentPool: AgentPool?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleStorageTransferV1.AgentPool

    /// See `StorageTransferServiceClient.getAgentPool`.
    func getAgentPool(request: GetAgentPoolRequest) async throws
      -> GoogleStorageTransferV1.AgentPool

    /// See `StorageTransferServiceClient.getAgentPool`.
    func getAgentPool(
      name: Swift.String,
    ) async throws -> GoogleStorageTransferV1.AgentPool

    /// See `StorageTransferServiceClient.listAgentPools`.
    func listAgentPools(request: ListAgentPoolsRequest) async throws
      -> GoogleStorageTransferV1.ListAgentPoolsResponse

    /// See `StorageTransferServiceClient.listAgentPools`.
    func listAgentPools(
      byItem: ListAgentPoolsRequest
    ) throws -> any AsyncSequence<AgentPool, Swift.Error>

    /// See `StorageTransferServiceClient.listAgentPools`.
    func listAgentPools(
      projectId: Swift.String,
    ) throws -> any AsyncSequence<AgentPool, Swift.Error>

    /// See `StorageTransferServiceClient.deleteAgentPool`.
    func deleteAgentPool(request: DeleteAgentPoolRequest) async throws

    /// See `StorageTransferServiceClient.deleteAgentPool`.
    func deleteAgentPool(
      name: Swift.String,
    ) async throws

    /// See `StorageTransferServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `StorageTransferServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `StorageTransferServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `StorageTransferServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `StorageTransferServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `StorageTransferServiceClient.getGoogleServiceAccount`.
    func getGoogleServiceAccount(
      request: GetGoogleServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.GoogleServiceAccount

    /// See `StorageTransferServiceClient.createTransferJob`.
    func createTransferJob(
      request: CreateTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.TransferJob

    /// See `StorageTransferServiceClient.updateTransferJob`.
    func updateTransferJob(
      request: UpdateTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.TransferJob

    /// See `StorageTransferServiceClient.getTransferJob`.
    func getTransferJob(
      request: GetTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.TransferJob

    /// See `StorageTransferServiceClient.listTransferJobs`.
    func listTransferJobs(
      request: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.ListTransferJobsResponse

    /// See `StorageTransferServiceClient.listTransferJobs`.
    func listTransferJobs(
      byItem: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<TransferJob, Swift.Error>

    /// See `StorageTransferServiceClient.pauseTransferOperation`.
    func pauseTransferOperation(
      request: PauseTransferOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `StorageTransferServiceClient.resumeTransferOperation`.
    func resumeTransferOperation(
      request: ResumeTransferOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `StorageTransferServiceClient.runTransferJob`.
    func runTransferJob(
      request: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `StorageTransferServiceClient.runTransferJob`.
    func runTransferJob(
      withPolling: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `StorageTransferServiceClient.deleteTransferJob`.
    func deleteTransferJob(
      request: DeleteTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `StorageTransferServiceClient.createAgentPool`.
    func createAgentPool(
      request: CreateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.AgentPool

    /// See `StorageTransferServiceClient.updateAgentPool`.
    func updateAgentPool(
      request: UpdateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.AgentPool

    /// See `StorageTransferServiceClient.getAgentPool`.
    func getAgentPool(
      request: GetAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.AgentPool

    /// See `StorageTransferServiceClient.listAgentPools`.
    func listAgentPools(
      request: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStorageTransferV1.ListAgentPoolsResponse

    /// See `StorageTransferServiceClient.listAgentPools`.
    func listAgentPools(
      byItem: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AgentPool, Swift.Error>

    /// See `StorageTransferServiceClient.deleteAgentPool`.
    func deleteAgentPool(
      request: DeleteAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `StorageTransferServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `StorageTransferServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `StorageTransferServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.StorageTransferServiceProtocol {
  public func getGoogleServiceAccount(request: GetGoogleServiceAccountRequest) async throws
    -> GoogleStorageTransferV1.GoogleServiceAccount
  {
    try await self.getGoogleServiceAccount(request: request, options: .init())
  }

  public func getGoogleServiceAccount(
    request: GetGoogleServiceAccountRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.GoogleServiceAccount {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createTransferJob(request: CreateTransferJobRequest) async throws
    -> GoogleStorageTransferV1.TransferJob
  {
    try await self.createTransferJob(request: request, options: .init())
  }

  public func createTransferJob(
    request: CreateTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.TransferJob {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateTransferJob(request: UpdateTransferJobRequest) async throws
    -> GoogleStorageTransferV1.TransferJob
  {
    try await self.updateTransferJob(request: request, options: .init())
  }

  public func updateTransferJob(
    request: UpdateTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.TransferJob {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getTransferJob(request: GetTransferJobRequest) async throws
    -> GoogleStorageTransferV1.TransferJob
  {
    try await self.getTransferJob(request: request, options: .init())
  }

  public func getTransferJob(
    request: GetTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.TransferJob {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTransferJobs(request: ListTransferJobsRequest) async throws
    -> GoogleStorageTransferV1.ListTransferJobsResponse
  {
    try await self.listTransferJobs(request: request, options: .init())
  }

  public func listTransferJobs(
    request: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.ListTransferJobsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTransferJobs(
    byItem: ListTransferJobsRequest
  ) throws -> any AsyncSequence<TransferJob, Swift.Error> {
    try self.listTransferJobs(byItem: byItem, options: .init())
  }

  public func listTransferJobs(
    byItem: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TransferJob, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleStorageTransferV1.ListTransferJobsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func pauseTransferOperation(request: PauseTransferOperationRequest) async throws {
    try await self.pauseTransferOperation(request: request, options: .init())
  }

  public func pauseTransferOperation(
    request: PauseTransferOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func resumeTransferOperation(request: ResumeTransferOperationRequest) async throws {
    try await self.resumeTransferOperation(request: request, options: .init())
  }

  public func resumeTransferOperation(
    request: ResumeTransferOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func runTransferJob(request: RunTransferJobRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.runTransferJob(request: request, options: .init())
  }

  public func runTransferJob(
    request: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func runTransferJob(withPolling: RunTransferJobRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Swift.Void>
  {
    try await self.runTransferJob(withPolling: withPolling, options: .init())
  }

  public func runTransferJob(
    withPolling: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteTransferJob(request: DeleteTransferJobRequest) async throws {
    try await self.deleteTransferJob(request: request, options: .init())
  }

  public func deleteTransferJob(
    request: DeleteTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createAgentPool(request: CreateAgentPoolRequest) async throws
    -> GoogleStorageTransferV1.AgentPool
  {
    try await self.createAgentPool(request: request, options: .init())
  }

  public func createAgentPool(
    request: CreateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.AgentPool {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createAgentPool(
    projectId: Swift.String,
    agentPool: AgentPool?,
    agentPoolId: Swift.String,
  ) async throws -> GoogleStorageTransferV1.AgentPool {
    let request = CreateAgentPoolRequest().with {
      $0.projectId = projectId
      $0.agentPool = agentPool
      $0.agentPoolId = agentPoolId
    }
    return try await self.createAgentPool(request: request)
  }

  public func updateAgentPool(request: UpdateAgentPoolRequest) async throws
    -> GoogleStorageTransferV1.AgentPool
  {
    try await self.updateAgentPool(request: request, options: .init())
  }

  public func updateAgentPool(
    request: UpdateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.AgentPool {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateAgentPool(
    agentPool: AgentPool?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleStorageTransferV1.AgentPool {
    let request = UpdateAgentPoolRequest().with {
      $0.agentPool = agentPool
      $0.updateMask = updateMask
    }
    return try await self.updateAgentPool(request: request)
  }

  public func getAgentPool(request: GetAgentPoolRequest) async throws
    -> GoogleStorageTransferV1.AgentPool
  {
    try await self.getAgentPool(request: request, options: .init())
  }

  public func getAgentPool(
    request: GetAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.AgentPool {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getAgentPool(
    name: Swift.String,
  ) async throws -> GoogleStorageTransferV1.AgentPool {
    let request = GetAgentPoolRequest().with {
      $0.name = name
    }
    return try await self.getAgentPool(request: request)
  }

  public func listAgentPools(request: ListAgentPoolsRequest) async throws
    -> GoogleStorageTransferV1.ListAgentPoolsResponse
  {
    try await self.listAgentPools(request: request, options: .init())
  }

  public func listAgentPools(
    request: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStorageTransferV1.ListAgentPoolsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAgentPools(
    byItem: ListAgentPoolsRequest
  ) throws -> any AsyncSequence<AgentPool, Swift.Error> {
    try self.listAgentPools(byItem: byItem, options: .init())
  }

  public func listAgentPools(
    byItem: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AgentPool, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleStorageTransferV1.ListAgentPoolsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAgentPools(
    projectId: Swift.String,
  ) throws -> any AsyncSequence<AgentPool, Swift.Error> {
    let request = ListAgentPoolsRequest().with {
      $0.projectId = projectId
    }
    return try self.listAgentPools(byItem: request)
  }

  public func deleteAgentPool(request: DeleteAgentPoolRequest) async throws {
    try await self.deleteAgentPool(request: request, options: .init())
  }

  public func deleteAgentPool(
    request: DeleteAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteAgentPool(
    name: Swift.String,
  ) async throws {
    let request = DeleteAgentPoolRequest().with {
      $0.name = name
    }
    try await self.deleteAgentPool(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
