// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import Logging

/// Storage Transfer Service and its protos.
/// Transfers data between between Google Cloud Storage buckets or from a data
/// source external to Google to a Cloud Storage bucket.
///
/// @Snippet(path: "StorageTransferServiceQuickstart")
public protocol StorageTransferService {
  /// Returns the Google service account that is used by Storage Transfer
  /// Service to access buckets in the project where transfers
  /// run or in other projects. Each Google service account is associated
  /// with one Google Cloud project. Users
  /// should add this service account to the Google Cloud Storage bucket
  /// ACLs to grant access to Storage Transfer Service. This service
  /// account is created and owned by Storage Transfer Service and can
  /// only be used by Storage Transfer Service.
  ///
  /// @Snippet(path: "StorageTransferService_GetGoogleServiceAccount")
  func getGoogleServiceAccount(request: GetGoogleServiceAccountRequest) async throws
    -> GoogleStoragetransferV1.GoogleServiceAccount

  /// Creates a transfer job that runs periodically.
  ///
  /// @Snippet(path: "StorageTransferService_CreateTransferJob")
  func createTransferJob(request: CreateTransferJobRequest) async throws
    -> GoogleStoragetransferV1.TransferJob

  /// Updates a transfer job. Updating a job's transfer spec does not affect
  /// transfer operations that are running already.
  ///
  /// **Note:** The job's [status][google.storagetransfer.v1.TransferJob.status]
  /// field can be modified using this RPC (for example, to set a job's status to
  /// [DELETED][google.storagetransfer.v1.TransferJob.Status.DELETED],
  /// [DISABLED][google.storagetransfer.v1.TransferJob.Status.DISABLED], or
  /// [ENABLED][google.storagetransfer.v1.TransferJob.Status.ENABLED]).
  ///
  /// [google.storagetransfer.v1.TransferJob.Status.DELETED]: <doc:TransferJob/Status/deleted>
  /// [google.storagetransfer.v1.TransferJob.Status.DISABLED]: <doc:TransferJob/Status/disabled>
  /// [google.storagetransfer.v1.TransferJob.Status.ENABLED]: <doc:TransferJob/Status/enabled>
  /// [google.storagetransfer.v1.TransferJob.status]: <doc:TransferJob/status>
  ///
  /// @Snippet(path: "StorageTransferService_UpdateTransferJob")
  func updateTransferJob(request: UpdateTransferJobRequest) async throws
    -> GoogleStoragetransferV1.TransferJob

  /// Gets a transfer job.
  ///
  /// @Snippet(path: "StorageTransferService_GetTransferJob")
  func getTransferJob(request: GetTransferJobRequest) async throws
    -> GoogleStoragetransferV1.TransferJob

  /// Lists transfer jobs.
  ///
  /// @Snippet(path: "StorageTransferService_ListTransferJobs")
  func listTransferJobs(request: ListTransferJobsRequest) async throws
    -> GoogleStoragetransferV1.ListTransferJobsResponse

  /// Lists transfer jobs.
  func listTransferJobs(
    byItem: ListTransferJobsRequest
  ) throws -> any AsyncSequence<TransferJob, Swift.Error>

  /// Pauses a transfer operation.
  ///
  /// @Snippet(path: "StorageTransferService_PauseTransferOperation")
  func pauseTransferOperation(request: PauseTransferOperationRequest) async throws

  /// Resumes a transfer operation that is paused.
  ///
  /// @Snippet(path: "StorageTransferService_ResumeTransferOperation")
  func resumeTransferOperation(request: ResumeTransferOperationRequest) async throws

  /// Starts a new operation for the specified transfer job.
  /// A `TransferJob` has a maximum of one active `TransferOperation`. If this
  /// method is called while a `TransferOperation` is active, an error is
  /// returned.
  ///
  /// @Snippet(path: "StorageTransferService_RunTransferJob")
  func runTransferJob(request: RunTransferJobRequest) async throws -> GoogleLongrunning.Operation

  /// Starts a new operation for the specified transfer job.
  /// A `TransferJob` has a maximum of one active `TransferOperation`. If this
  /// method is called while a `TransferOperation` is active, an error is
  /// returned.
  func runTransferJob(withPolling: RunTransferJobRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>

  /// Deletes a transfer job. Deleting a transfer job sets its status to
  /// [DELETED][google.storagetransfer.v1.TransferJob.Status.DELETED].
  ///
  /// [google.storagetransfer.v1.TransferJob.Status.DELETED]: <doc:TransferJob/Status/deleted>
  ///
  /// @Snippet(path: "StorageTransferService_DeleteTransferJob")
  func deleteTransferJob(request: DeleteTransferJobRequest) async throws

  /// Creates an agent pool resource.
  ///
  /// @Snippet(path: "StorageTransferService_CreateAgentPool")
  func createAgentPool(request: CreateAgentPoolRequest) async throws
    -> GoogleStoragetransferV1.AgentPool

  /// Updates an existing agent pool resource.
  ///
  /// @Snippet(path: "StorageTransferService_UpdateAgentPool")
  func updateAgentPool(request: UpdateAgentPoolRequest) async throws
    -> GoogleStoragetransferV1.AgentPool

  /// Gets an agent pool.
  ///
  /// @Snippet(path: "StorageTransferService_GetAgentPool")
  func getAgentPool(request: GetAgentPoolRequest) async throws -> GoogleStoragetransferV1.AgentPool

  /// Lists agent pools.
  ///
  /// @Snippet(path: "StorageTransferService_ListAgentPools")
  func listAgentPools(request: ListAgentPoolsRequest) async throws
    -> GoogleStoragetransferV1.ListAgentPoolsResponse

  /// Lists agent pools.
  func listAgentPools(
    byItem: ListAgentPoolsRequest
  ) throws -> any AsyncSequence<AgentPool, Swift.Error>

  /// Deletes an agent pool.
  ///
  /// @Snippet(path: "StorageTransferService_DeleteAgentPool")
  func deleteAgentPool(request: DeleteAgentPoolRequest) async throws

  /// Lists transfer operations. Operations are ordered by their creation
  /// time in reverse chronological order.
  ///
  /// @Snippet(path: "StorageTransferService_ListOperations")
  func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse

  /// Lists transfer operations. Operations are ordered by their creation
  /// time in reverse chronological order.
  func listOperations(
    byItem: ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageTransferService_GetOperation")
  func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Cancels a transfer. Use
  /// the [transferOperations.get][google.longrunning.Operations.GetOperation]
  /// method to check if the cancellation succeeded or if the operation
  /// completed despite the `cancel` request.
  ///
  /// When you cancel an operation, the currently running transfer is
  /// interrupted.  For recurring transfer jobs, the next instance of the
  /// transfer job will still run.  For example, if your job is configured
  /// to run every day at 1pm and you cancel Monday's operation at 1:05pm,
  /// Monday's transfer
  /// will stop. However, a transfer job will still be attempted on Tuesday.
  ///
  /// This applies only to currently running operations. If an operation is
  /// not currently running, `cancel` does nothing.
  ///
  /// <aside class="caution">
  /// <b>Caution:</b> Canceling a transfer job can leave your data in an
  /// unknown state. We recommend that you restore the state at both the
  /// destination and the source after the `cancel` request completes so
  /// that your data is in a consistent state. </aside>
  ///
  /// When you cancel a job, the next job computes a delta of files and may
  /// repair any inconsistent state. For instance, if you run a job every
  /// day, and today's job found 10 new files and transferred five files
  /// before you canceled the job, tomorrow's transfer operation will
  /// compute a new delta with the five files that were not copied today
  /// plus any new files discovered tomorrow.
  ///
  /// @Snippet(path: "StorageTransferService_CancelOperation")
  func cancelOperation(request: CancelOperationRequest) async throws

  /// Returns the Google service account that is used by Storage Transfer
  /// Service to access buckets in the project where transfers
  /// run or in other projects. Each Google service account is associated
  /// with one Google Cloud project. Users
  /// should add this service account to the Google Cloud Storage bucket
  /// ACLs to grant access to Storage Transfer Service. This service
  /// account is created and owned by Storage Transfer Service and can
  /// only be used by Storage Transfer Service.
  ///
  /// @Snippet(path: "StorageTransferService_GetGoogleServiceAccount")
  func getGoogleServiceAccount(
    request: GetGoogleServiceAccountRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.GoogleServiceAccount

  /// Creates a transfer job that runs periodically.
  ///
  /// @Snippet(path: "StorageTransferService_CreateTransferJob")
  func createTransferJob(
    request: CreateTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.TransferJob

  /// Updates a transfer job. Updating a job's transfer spec does not affect
  /// transfer operations that are running already.
  ///
  /// **Note:** The job's [status][google.storagetransfer.v1.TransferJob.status]
  /// field can be modified using this RPC (for example, to set a job's status to
  /// [DELETED][google.storagetransfer.v1.TransferJob.Status.DELETED],
  /// [DISABLED][google.storagetransfer.v1.TransferJob.Status.DISABLED], or
  /// [ENABLED][google.storagetransfer.v1.TransferJob.Status.ENABLED]).
  ///
  /// [google.storagetransfer.v1.TransferJob.Status.DELETED]: <doc:TransferJob/Status/deleted>
  /// [google.storagetransfer.v1.TransferJob.Status.DISABLED]: <doc:TransferJob/Status/disabled>
  /// [google.storagetransfer.v1.TransferJob.Status.ENABLED]: <doc:TransferJob/Status/enabled>
  /// [google.storagetransfer.v1.TransferJob.status]: <doc:TransferJob/status>
  ///
  /// @Snippet(path: "StorageTransferService_UpdateTransferJob")
  func updateTransferJob(
    request: UpdateTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.TransferJob

  /// Gets a transfer job.
  ///
  /// @Snippet(path: "StorageTransferService_GetTransferJob")
  func getTransferJob(
    request: GetTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.TransferJob

  /// Lists transfer jobs.
  ///
  /// @Snippet(path: "StorageTransferService_ListTransferJobs")
  func listTransferJobs(
    request: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.ListTransferJobsResponse

  /// Lists transfer jobs.
  func listTransferJobs(
    byItem: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TransferJob, Swift.Error>

  /// Pauses a transfer operation.
  ///
  /// @Snippet(path: "StorageTransferService_PauseTransferOperation")
  func pauseTransferOperation(
    request: PauseTransferOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws

  /// Resumes a transfer operation that is paused.
  ///
  /// @Snippet(path: "StorageTransferService_ResumeTransferOperation")
  func resumeTransferOperation(
    request: ResumeTransferOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws

  /// Starts a new operation for the specified transfer job.
  /// A `TransferJob` has a maximum of one active `TransferOperation`. If this
  /// method is called while a `TransferOperation` is active, an error is
  /// returned.
  ///
  /// @Snippet(path: "StorageTransferService_RunTransferJob")
  func runTransferJob(
    request: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Starts a new operation for the specified transfer job.
  /// A `TransferJob` has a maximum of one active `TransferOperation`. If this
  /// method is called while a `TransferOperation` is active, an error is
  /// returned.
  func runTransferJob(
    withPolling: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void>

  /// Deletes a transfer job. Deleting a transfer job sets its status to
  /// [DELETED][google.storagetransfer.v1.TransferJob.Status.DELETED].
  ///
  /// [google.storagetransfer.v1.TransferJob.Status.DELETED]: <doc:TransferJob/Status/deleted>
  ///
  /// @Snippet(path: "StorageTransferService_DeleteTransferJob")
  func deleteTransferJob(
    request: DeleteTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws

  /// Creates an agent pool resource.
  ///
  /// @Snippet(path: "StorageTransferService_CreateAgentPool")
  func createAgentPool(
    request: CreateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.AgentPool

  /// Updates an existing agent pool resource.
  ///
  /// @Snippet(path: "StorageTransferService_UpdateAgentPool")
  func updateAgentPool(
    request: UpdateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.AgentPool

  /// Gets an agent pool.
  ///
  /// @Snippet(path: "StorageTransferService_GetAgentPool")
  func getAgentPool(
    request: GetAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.AgentPool

  /// Lists agent pools.
  ///
  /// @Snippet(path: "StorageTransferService_ListAgentPools")
  func listAgentPools(
    request: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.ListAgentPoolsResponse

  /// Lists agent pools.
  func listAgentPools(
    byItem: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AgentPool, Swift.Error>

  /// Deletes an agent pool.
  ///
  /// @Snippet(path: "StorageTransferService_DeleteAgentPool")
  func deleteAgentPool(
    request: DeleteAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws

  /// Lists transfer operations. Operations are ordered by their creation
  /// time in reverse chronological order.
  ///
  /// @Snippet(path: "StorageTransferService_ListOperations")
  func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse

  /// Lists transfer operations. Operations are ordered by their creation
  /// time in reverse chronological order.
  func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "StorageTransferService_GetOperation")
  func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Cancels a transfer. Use
  /// the [transferOperations.get][google.longrunning.Operations.GetOperation]
  /// method to check if the cancellation succeeded or if the operation
  /// completed despite the `cancel` request.
  ///
  /// When you cancel an operation, the currently running transfer is
  /// interrupted.  For recurring transfer jobs, the next instance of the
  /// transfer job will still run.  For example, if your job is configured
  /// to run every day at 1pm and you cancel Monday's operation at 1:05pm,
  /// Monday's transfer
  /// will stop. However, a transfer job will still be attempted on Tuesday.
  ///
  /// This applies only to currently running operations. If an operation is
  /// not currently running, `cancel` does nothing.
  ///
  /// <aside class="caution">
  /// <b>Caution:</b> Canceling a transfer job can leave your data in an
  /// unknown state. We recommend that you restore the state at both the
  /// destination and the source after the `cancel` request completes so
  /// that your data is in a consistent state. </aside>
  ///
  /// When you cancel a job, the next job computes a delta of files and may
  /// repair any inconsistent state. For instance, if you run a job every
  /// day, and today's job found 10 new files and transferred five files
  /// before you canceled the job, tomorrow's transfer operation will
  /// compute a new delta with the five files that were not copied today
  /// plus any new files discovered tomorrow.
  ///
  /// @Snippet(path: "StorageTransferService_CancelOperation")
  func cancelOperation(
    request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws
}

extension Clients {
  /// The recommended implementation for ``StorageTransferService``.
  public class StorageTransferServiceClient: StorageTransferService {
    let inner: any StorageTransferServiceStub

    /// Creates a new `StorageTransferServiceClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any StorageTransferServiceStub = try StorageTransferServiceTransport(options)
      inner = StorageTransferServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = StorageTransferServiceLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// See `StorageTransferService.getGoogleServiceAccount`
    public func getGoogleServiceAccount(
      request: GetGoogleServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.GoogleServiceAccount {
      try await self.inner.getGoogleServiceAccount(request: request, options: options)
    }

    /// See `StorageTransferService.createTransferJob`
    public func createTransferJob(
      request: CreateTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.TransferJob {
      try await self.inner.createTransferJob(request: request, options: options)
    }

    /// See `StorageTransferService.updateTransferJob`
    public func updateTransferJob(
      request: UpdateTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.TransferJob {
      try await self.inner.updateTransferJob(request: request, options: options)
    }

    /// See `StorageTransferService.getTransferJob`
    public func getTransferJob(
      request: GetTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.TransferJob {
      try await self.inner.getTransferJob(request: request, options: options)
    }

    /// See `StorageTransferService.listTransferJobs`
    public func listTransferJobs(
      request: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.ListTransferJobsResponse {
      try await self.inner.listTransferJobs(request: request, options: options)
    }

    /// Lists transfer jobs.
    public func listTransferJobs(
      byItem: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<TransferJob, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleStoragetransferV1.ListTransferJobsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listTransferJobs(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `StorageTransferService.pauseTransferOperation`
    public func pauseTransferOperation(
      request: PauseTransferOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.pauseTransferOperation(request: request, options: options)
    }

    /// See `StorageTransferService.resumeTransferOperation`
    public func resumeTransferOperation(
      request: ResumeTransferOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.resumeTransferOperation(request: request, options: options)
    }

    /// See `StorageTransferService.runTransferJob`
    public func runTransferJob(
      request: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.runTransferJob(request: request, options: options)
    }

    /// Starts a new operation for the specified transfer job.
    /// A `TransferJob` has a maximum of one active `TransferOperation`. If this
    /// method is called while a `TransferOperation` is active, an error is
    /// returned.
    public func runTransferJob(
      withPolling: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Void>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response:
          return .init(done: true, result: .success(()))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.runTransferJob(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `StorageTransferService.deleteTransferJob`
    public func deleteTransferJob(
      request: DeleteTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteTransferJob(request: request, options: options)
    }

    /// See `StorageTransferService.createAgentPool`
    public func createAgentPool(
      request: CreateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.AgentPool {
      try await self.inner.createAgentPool(request: request, options: options)
    }

    /// See `StorageTransferService.updateAgentPool`
    public func updateAgentPool(
      request: UpdateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.AgentPool {
      try await self.inner.updateAgentPool(request: request, options: options)
    }

    /// See `StorageTransferService.getAgentPool`
    public func getAgentPool(
      request: GetAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.AgentPool {
      try await self.inner.getAgentPool(request: request, options: options)
    }

    /// See `StorageTransferService.listAgentPools`
    public func listAgentPools(
      request: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.ListAgentPoolsResponse {
      try await self.inner.listAgentPools(request: request, options: options)
    }

    /// Lists agent pools.
    public func listAgentPools(
      byItem: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AgentPool, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleStoragetransferV1.ListAgentPoolsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listAgentPools(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `StorageTransferService.deleteAgentPool`
    public func deleteAgentPool(
      request: DeleteAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteAgentPool(request: request, options: options)
    }

    /// See `StorageTransferService.listOperations`
    public func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Lists transfer operations. Operations are ordered by their creation
    /// time in reverse chronological order.
    public func listOperations(
      byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `StorageTransferService.getOperation`
    public func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// See `StorageTransferService.cancelOperation`
    public func cancelOperation(
      request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }
  }
}

// Default implementations
extension StorageTransferService {
  public func getGoogleServiceAccount(request: GetGoogleServiceAccountRequest) async throws
    -> GoogleStoragetransferV1.GoogleServiceAccount
  {
    try await self.getGoogleServiceAccount(request: request, options: .init())
  }

  public func getGoogleServiceAccount(
    request: GetGoogleServiceAccountRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.GoogleServiceAccount {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createTransferJob(request: CreateTransferJobRequest) async throws
    -> GoogleStoragetransferV1.TransferJob
  {
    try await self.createTransferJob(request: request, options: .init())
  }

  public func createTransferJob(
    request: CreateTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.TransferJob {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateTransferJob(request: UpdateTransferJobRequest) async throws
    -> GoogleStoragetransferV1.TransferJob
  {
    try await self.updateTransferJob(request: request, options: .init())
  }

  public func updateTransferJob(
    request: UpdateTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.TransferJob {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getTransferJob(request: GetTransferJobRequest) async throws
    -> GoogleStoragetransferV1.TransferJob
  {
    try await self.getTransferJob(request: request, options: .init())
  }

  public func getTransferJob(
    request: GetTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.TransferJob {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTransferJobs(request: ListTransferJobsRequest) async throws
    -> GoogleStoragetransferV1.ListTransferJobsResponse
  {
    try await self.listTransferJobs(request: request, options: .init())
  }

  public func listTransferJobs(
    request: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.ListTransferJobsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTransferJobs(
    byItem: ListTransferJobsRequest
  ) throws -> any AsyncSequence<TransferJob, Swift.Error> {
    try self.listTransferJobs(byItem: byItem, options: .init())
  }

  public func listTransferJobs(
    byItem: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<TransferJob, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleStoragetransferV1.ListTransferJobsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func pauseTransferOperation(request: PauseTransferOperationRequest) async throws {
    try await self.pauseTransferOperation(request: request, options: .init())
  }

  public func pauseTransferOperation(
    request: PauseTransferOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func resumeTransferOperation(request: ResumeTransferOperationRequest) async throws {
    try await self.resumeTransferOperation(request: request, options: .init())
  }

  public func resumeTransferOperation(
    request: ResumeTransferOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func runTransferJob(request: RunTransferJobRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.runTransferJob(request: request, options: .init())
  }

  public func runTransferJob(
    request: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func runTransferJob(withPolling: RunTransferJobRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.runTransferJob(withPolling: withPolling, options: .init())
  }

  public func runTransferJob(
    withPolling: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteTransferJob(request: DeleteTransferJobRequest) async throws {
    try await self.deleteTransferJob(request: request, options: .init())
  }

  public func deleteTransferJob(
    request: DeleteTransferJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createAgentPool(request: CreateAgentPoolRequest) async throws
    -> GoogleStoragetransferV1.AgentPool
  {
    try await self.createAgentPool(request: request, options: .init())
  }

  public func createAgentPool(
    request: CreateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.AgentPool {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateAgentPool(request: UpdateAgentPoolRequest) async throws
    -> GoogleStoragetransferV1.AgentPool
  {
    try await self.updateAgentPool(request: request, options: .init())
  }

  public func updateAgentPool(
    request: UpdateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.AgentPool {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getAgentPool(request: GetAgentPoolRequest) async throws
    -> GoogleStoragetransferV1.AgentPool
  {
    try await self.getAgentPool(request: request, options: .init())
  }

  public func getAgentPool(
    request: GetAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.AgentPool {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAgentPools(request: ListAgentPoolsRequest) async throws
    -> GoogleStoragetransferV1.ListAgentPoolsResponse
  {
    try await self.listAgentPools(request: request, options: .init())
  }

  public func listAgentPools(
    request: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleStoragetransferV1.ListAgentPoolsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAgentPools(
    byItem: ListAgentPoolsRequest
  ) throws -> any AsyncSequence<AgentPool, Swift.Error> {
    try self.listAgentPools(byItem: byItem, options: .init())
  }

  public func listAgentPools(
    byItem: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AgentPool, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleStoragetransferV1.ListAgentPoolsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func deleteAgentPool(request: DeleteAgentPoolRequest) async throws {
    try await self.deleteAgentPool(request: request, options: .init())
  }

  public func deleteAgentPool(
    request: DeleteAgentPoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(request: CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
