// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class StorageTransferServiceLogging: StorageTransferServiceStub {
    let inner: any StorageTransferServiceStub
    let logger: Logger

    public init(_ inner: any StorageTransferServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "GoogleStoragetransferV1"
      logger[metadataKey: "gcp.client.service"] = "storagetransfer"
      logger[metadataKey: "gcp.experimental.swift.client"] = "StorageTransferService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func getGoogleServiceAccount(
      request: GetGoogleServiceAccountRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.GoogleServiceAccount {
      try await self._intercept(
        request: request,
        options: options,
        name: "getGoogleServiceAccount",
        action: {
          (r: GetGoogleServiceAccountRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleStoragetransferV1.GoogleServiceAccount
          in
          return try await self.inner.getGoogleServiceAccount(request: r, options: o)
        })
    }

    public func createTransferJob(
      request: CreateTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.TransferJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTransferJob",
        action: {
          (r: CreateTransferJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleStoragetransferV1.TransferJob
          in
          return try await self.inner.createTransferJob(request: r, options: o)
        })
    }

    public func updateTransferJob(
      request: UpdateTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.TransferJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTransferJob",
        action: {
          (r: UpdateTransferJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleStoragetransferV1.TransferJob
          in
          return try await self.inner.updateTransferJob(request: r, options: o)
        })
    }

    public func getTransferJob(
      request: GetTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.TransferJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTransferJob",
        action: {
          (r: GetTransferJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleStoragetransferV1.TransferJob
          in
          return try await self.inner.getTransferJob(request: r, options: o)
        })
    }

    public func listTransferJobs(
      request: ListTransferJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.ListTransferJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTransferJobs",
        action: {
          (r: ListTransferJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleStoragetransferV1.ListTransferJobsResponse
          in
          return try await self.inner.listTransferJobs(request: r, options: o)
        })
    }

    public func pauseTransferOperation(
      request: PauseTransferOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "pauseTransferOperation",
        action: {
          (r: PauseTransferOperationRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.pauseTransferOperation(request: r, options: o)
        })
    }

    public func resumeTransferOperation(
      request: ResumeTransferOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "resumeTransferOperation",
        action: {
          (r: ResumeTransferOperationRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.resumeTransferOperation(request: r, options: o)
        })
    }

    public func runTransferJob(
      request: RunTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "runTransferJob",
        action: {
          (r: RunTransferJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.runTransferJob(request: r, options: o)
        })
    }

    public func deleteTransferJob(
      request: DeleteTransferJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTransferJob",
        action: {
          (r: DeleteTransferJobRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTransferJob(request: r, options: o)
        })
    }

    public func createAgentPool(
      request: CreateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.AgentPool {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAgentPool",
        action: {
          (r: CreateAgentPoolRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleStoragetransferV1.AgentPool
          in
          return try await self.inner.createAgentPool(request: r, options: o)
        })
    }

    public func updateAgentPool(
      request: UpdateAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.AgentPool {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateAgentPool",
        action: {
          (r: UpdateAgentPoolRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleStoragetransferV1.AgentPool
          in
          return try await self.inner.updateAgentPool(request: r, options: o)
        })
    }

    public func getAgentPool(
      request: GetAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.AgentPool {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAgentPool",
        action: {
          (r: GetAgentPoolRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleStoragetransferV1.AgentPool
          in
          return try await self.inner.getAgentPool(request: r, options: o)
        })
    }

    public func listAgentPools(
      request: ListAgentPoolsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleStoragetransferV1.ListAgentPoolsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAgentPools",
        action: {
          (r: ListAgentPoolsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleStoragetransferV1.ListAgentPoolsResponse
          in
          return try await self.inner.listAgentPools(request: r, options: o)
        })
    }

    public func deleteAgentPool(
      request: DeleteAgentPoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAgentPool",
        action: {
          (r: DeleteAgentPoolRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAgentPool(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongrunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongrunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
