// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Configuration for running a transfer.
public struct TransferSpec: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Only objects that satisfy these object conditions are included in the set
  /// of data source and data sink objects.  Object conditions based on
  /// objects' "last modification time" do not exclude objects in a data sink.
  public var objectConditions: ObjectConditions? = nil

  /// If the option
  /// [delete_objects_unique_in_sink][google.storagetransfer.v1.TransferOptions.delete_objects_unique_in_sink]
  /// is `true` and time-based object conditions such as 'last modification time'
  /// are specified, the request fails with an
  /// [INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT] error.
  ///
  /// [google.rpc.Code.INVALID_ARGUMENT]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Code/invalidArgument
  /// [google.storagetransfer.v1.TransferOptions.delete_objects_unique_in_sink]: <doc:TransferOptions/deleteObjectsUniqueInSink>
  public var transferOptions: TransferOptions? = nil

  /// A manifest file provides a list of objects to be transferred from the data
  /// source. This field points to the location of the manifest file.
  /// Otherwise, the entire source bucket is used. ObjectConditions still apply.
  public var transferManifest: TransferManifest? = nil

  /// Specifies the agent pool name associated with the posix data source. When
  /// unspecified, the default name is used.
  public var sourceAgentPoolName: Swift.String = Swift.String()

  /// Specifies the agent pool name associated with the posix data sink. When
  /// unspecified, the default name is used.
  public var sinkAgentPoolName: Swift.String = Swift.String()

  /// The write sink for the data.
  public var dataSink: OneOf_DataSink? = nil

  /// The read source of the data.
  public var dataSource: OneOf_DataSource? = nil

  public var intermediateDataLocation: OneOf_IntermediateDataLocation? = nil

  /// Initialize a new instance of `TransferSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferSpec().with { $0.gcsDataSink = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcsDataSink = "gcsDataSink"
    case posixDataSink = "posixDataSink"
    case gcsDataSource = "gcsDataSource"
    case awsS3DataSource = "awsS3DataSource"
    case httpDataSource = "httpDataSource"
    case posixDataSource = "posixDataSource"
    case azureBlobStorageDataSource = "azureBlobStorageDataSource"
    case awsS3CompatibleDataSource = "awsS3CompatibleDataSource"
    case hdfsDataSource = "hdfsDataSource"
    case gcsIntermediateDataLocation = "gcsIntermediateDataLocation"
    case objectConditions = "objectConditions"
    case transferOptions = "transferOptions"
    case transferManifest = "transferManifest"
    case sourceAgentPoolName = "sourceAgentPoolName"
    case sinkAgentPoolName = "sinkAgentPoolName"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.objectConditions = try container.decodeIfPresent(
      ObjectConditions.self, forKey: .objectConditions)
    self.transferOptions = try container.decodeIfPresent(
      TransferOptions.self, forKey: .transferOptions)
    self.transferManifest = try container.decodeIfPresent(
      TransferManifest.self, forKey: .transferManifest)
    self.sourceAgentPoolName = try container.decode(Swift.String.self, forKey: .sourceAgentPoolName)
    self.sinkAgentPoolName = try container.decode(Swift.String.self, forKey: .sinkAgentPoolName)

    var dataSink: OneOf_DataSink? = nil
    let dataSinkCheckAndSet = {
      if dataSink != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'dataSink'"))
      }
      dataSink = $0
    }
    if let gcsDataSink = try container.decodeIfPresent(GcsData?.self, forKey: .gcsDataSink) {
      try dataSinkCheckAndSet(.gcsDataSink(gcsDataSink))
    }
    if let posixDataSink = try container.decodeIfPresent(
      PosixFilesystem?.self, forKey: .posixDataSink)
    {
      try dataSinkCheckAndSet(.posixDataSink(posixDataSink))
    }
    self.dataSink = dataSink

    var dataSource: OneOf_DataSource? = nil
    let dataSourceCheckAndSet = {
      if dataSource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'dataSource'"))
      }
      dataSource = $0
    }
    if let gcsDataSource = try container.decodeIfPresent(GcsData?.self, forKey: .gcsDataSource) {
      try dataSourceCheckAndSet(.gcsDataSource(gcsDataSource))
    }
    if let awsS3DataSource = try container.decodeIfPresent(
      AwsS3Data?.self, forKey: .awsS3DataSource)
    {
      try dataSourceCheckAndSet(.awsS3DataSource(awsS3DataSource))
    }
    if let httpDataSource = try container.decodeIfPresent(HttpData?.self, forKey: .httpDataSource) {
      try dataSourceCheckAndSet(.httpDataSource(httpDataSource))
    }
    if let posixDataSource = try container.decodeIfPresent(
      PosixFilesystem?.self, forKey: .posixDataSource)
    {
      try dataSourceCheckAndSet(.posixDataSource(posixDataSource))
    }
    if let azureBlobStorageDataSource = try container.decodeIfPresent(
      AzureBlobStorageData?.self, forKey: .azureBlobStorageDataSource)
    {
      try dataSourceCheckAndSet(.azureBlobStorageDataSource(azureBlobStorageDataSource))
    }
    if let awsS3CompatibleDataSource = try container.decodeIfPresent(
      AwsS3CompatibleData?.self, forKey: .awsS3CompatibleDataSource)
    {
      try dataSourceCheckAndSet(.awsS3CompatibleDataSource(awsS3CompatibleDataSource))
    }
    if let hdfsDataSource = try container.decodeIfPresent(HdfsData?.self, forKey: .hdfsDataSource) {
      try dataSourceCheckAndSet(.hdfsDataSource(hdfsDataSource))
    }
    self.dataSource = dataSource

    var intermediateDataLocation: OneOf_IntermediateDataLocation? = nil
    let intermediateDataLocationCheckAndSet = {
      if intermediateDataLocation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'intermediateDataLocation'"))
      }
      intermediateDataLocation = $0
    }
    if let gcsIntermediateDataLocation = try container.decodeIfPresent(
      GcsData?.self, forKey: .gcsIntermediateDataLocation)
    {
      try intermediateDataLocationCheckAndSet(
        .gcsIntermediateDataLocation(gcsIntermediateDataLocation))
    }
    self.intermediateDataLocation = intermediateDataLocation
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.objectConditions, forKey: .objectConditions)
    try container.encode(self.transferOptions, forKey: .transferOptions)
    try container.encode(self.transferManifest, forKey: .transferManifest)
    try container.encode(self.sourceAgentPoolName, forKey: .sourceAgentPoolName)
    try container.encode(self.sinkAgentPoolName, forKey: .sinkAgentPoolName)

    if let choice = self.dataSink {
      switch choice {
      case .gcsDataSink(let value):
        try container.encode(value, forKey: .gcsDataSink)
      case .posixDataSink(let value):
        try container.encode(value, forKey: .posixDataSink)
      }
    }

    if let choice = self.dataSource {
      switch choice {
      case .gcsDataSource(let value):
        try container.encode(value, forKey: .gcsDataSource)
      case .awsS3DataSource(let value):
        try container.encode(value, forKey: .awsS3DataSource)
      case .httpDataSource(let value):
        try container.encode(value, forKey: .httpDataSource)
      case .posixDataSource(let value):
        try container.encode(value, forKey: .posixDataSource)
      case .azureBlobStorageDataSource(let value):
        try container.encode(value, forKey: .azureBlobStorageDataSource)
      case .awsS3CompatibleDataSource(let value):
        try container.encode(value, forKey: .awsS3CompatibleDataSource)
      case .hdfsDataSource(let value):
        try container.encode(value, forKey: .hdfsDataSource)
      }
    }

    if let choice = self.intermediateDataLocation {
      switch choice {
      case .gcsIntermediateDataLocation(let value):
        try container.encode(value, forKey: .gcsIntermediateDataLocation)
      }
    }
  }

  /// The write sink for the data.
  public enum OneOf_DataSink: Codable, Equatable, Sendable {
    /// A Cloud Storage data sink.
    indirect case gcsDataSink(GcsData?)
    /// A POSIX Filesystem data sink.
    indirect case posixDataSink(PosixFilesystem?)
  }

  /// The read source of the data.
  public enum OneOf_DataSource: Codable, Equatable, Sendable {
    /// A Cloud Storage data source.
    indirect case gcsDataSource(GcsData?)
    /// An AWS S3 data source.
    indirect case awsS3DataSource(AwsS3Data?)
    /// An HTTP URL data source.
    indirect case httpDataSource(HttpData?)
    /// A POSIX Filesystem data source.
    indirect case posixDataSource(PosixFilesystem?)
    /// An Azure Blob Storage data source.
    indirect case azureBlobStorageDataSource(AzureBlobStorageData?)
    /// An AWS S3 compatible data source.
    indirect case awsS3CompatibleDataSource(AwsS3CompatibleData?)
    /// An HDFS cluster data source.
    indirect case hdfsDataSource(HdfsData?)
  }

  public enum OneOf_IntermediateDataLocation: Codable, Equatable, Sendable {
    /// For transfers between file systems, specifies a Cloud Storage bucket
    /// to be used as an intermediate location through which to transfer data.
    ///
    /// See [Transfer data between file
    /// systems](https://cloud.google.com/storage-transfer/docs/file-to-file) for
    /// more information.
    indirect case gcsIntermediateDataLocation(GcsData?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.TransferSpec"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
