// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// This resource represents the configuration of a transfer job that runs
/// periodically.
public struct TransferJob: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A unique name (within the transfer project) assigned when the job is
  /// created.  If this field is empty in a CreateTransferJobRequest, Storage
  /// Transfer Service assigns a unique name. Otherwise, the specified name
  /// is used as the unique name for this job.
  ///
  /// If the specified name is in use by a job, the creation request fails with
  /// an [ALREADY_EXISTS][google.rpc.Code.ALREADY_EXISTS] error.
  ///
  /// This name must start with `"transferJobs/"` prefix and end with a letter or
  /// a number, and should be no more than 128 characters. For transfers
  /// involving PosixFilesystem, this name must start with `transferJobs/OPI`
  /// specifically. For all other transfer types, this name must not start with
  /// `transferJobs/OPI`.
  ///
  /// Non-PosixFilesystem example:
  /// `"transferJobs/^(?!OPI)[A-Za-z0-9-._~]*[A-Za-z0-9]$"`
  ///
  /// PosixFilesystem example:
  /// `"transferJobs/OPI^[A-Za-z0-9-._~]*[A-Za-z0-9]$"`
  ///
  /// Applications must not rely on the enforcement of naming requirements
  /// involving OPI.
  ///
  /// Invalid job names fail with an
  /// [INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT] error.
  ///
  /// [google.rpc.Code.ALREADY_EXISTS]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Code/alreadyExists
  /// [google.rpc.Code.INVALID_ARGUMENT]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Code/invalidArgument
  public var name: Swift.String = Swift.String()

  /// A description provided by the user for the job. Its max length is 1024
  /// bytes when Unicode-encoded.
  public var description: Swift.String = Swift.String()

  /// The ID of the Google Cloud project that owns the job.
  public var projectId: Swift.String = Swift.String()

  /// Optional. The user-managed service account to which to delegate service
  /// agent permissions. You can grant Cloud Storage bucket permissions to this
  /// service account instead of to the Transfer Service service agent.
  ///
  /// Format is
  /// `projects/-/serviceAccounts/ACCOUNT_EMAIL_OR_UNIQUEID`
  ///
  /// Either the service account email
  /// (`SERVICE_ACCOUNT_NAME@PROJECT_ID.iam.gserviceaccount.com`) or the unique
  /// ID (`123456789012345678901`) are accepted in the string. The `-`
  /// wildcard character is required; replacing it with a project ID is invalid.
  ///
  /// See
  /// https://cloud.google.com//storage-transfer/docs/delegate-service-agent-permissions
  /// for required permissions.
  public var serviceAccount: Swift.String = Swift.String()

  /// Transfer specification.
  public var transferSpec: TransferSpec? = nil

  /// Replication specification.
  public var replicationSpec: ReplicationSpec? = nil

  /// Notification configuration.
  public var notificationConfig: NotificationConfig? = nil

  /// Logging configuration.
  public var loggingConfig: LoggingConfig? = nil

  /// Specifies schedule for the transfer job.
  /// This is an optional field. When the field is not set, the job never
  /// executes a transfer, unless you invoke RunTransferJob or update the job to
  /// have a non-empty schedule.
  public var schedule: Schedule? = nil

  /// Specifies the event stream for the transfer job for event-driven transfers.
  /// When EventStream is specified, the Schedule fields are ignored.
  public var eventStream: EventStream? = nil

  /// Status of the job. This value MUST be specified for
  /// `CreateTransferJobRequests`.
  ///
  /// **Note:** The effect of the new job status takes place during a subsequent
  /// job run. For example, if you change the job status from
  /// [ENABLED][google.storagetransfer.v1.TransferJob.Status.ENABLED] to
  /// [DISABLED][google.storagetransfer.v1.TransferJob.Status.DISABLED], and an
  /// operation spawned by the transfer is running, the status change would not
  /// affect the current operation.
  ///
  /// [google.storagetransfer.v1.TransferJob.Status.DISABLED]: <doc:TransferJob/Status/disabled>
  /// [google.storagetransfer.v1.TransferJob.Status.ENABLED]: <doc:TransferJob/Status/enabled>
  public var status: TransferJob.Status = TransferJob.Status()

  /// Output only. The time that the transfer job was created.
  public var creationTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time that the transfer job was last modified.
  public var lastModificationTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time that the transfer job was deleted.
  public var deletionTime: GoogleCloudWkt.Timestamp? = nil

  /// The name of the most recently started TransferOperation of this JobConfig.
  /// Present if a TransferOperation has been created for this JobConfig.
  public var latestOperationName: Swift.String = Swift.String()

  /// Initialize a new instance of `TransferJob`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferJob().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The status of the transfer job.
  public enum Status: Codable, Equatable, Sendable {
    case unspecified
    case enabled
    case disabled
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enabled: return 1
      case .disabled: return 2
      case .deleted: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STATUS_UNSPECIFIED"
      case .enabled: return "ENABLED"
      case .disabled: return "DISABLED"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STATUS_UNSPECIFIED": self = .unspecified
      case "ENABLED": self = .enabled
      case "DISABLED": self = .disabled
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enabled
      case 2: self = .disabled
      case 3: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .enabled: return try container.encode(1)
      case .disabled: return try container.encode(2)
      case .deleted: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.storagetransfer.v1.TransferJob"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
