// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A collection of counters that report the progress of a transfer operation.
public struct TransferCounters: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Objects found in the data source that are scheduled to be transferred,
  /// excluding any that are filtered based on object conditions or skipped due
  /// to sync.
  public var objectsFoundFromSource: Swift.Int64 = Swift.Int64()

  /// Bytes found in the data source that are scheduled to be transferred,
  /// excluding any that are filtered based on object conditions or skipped due
  /// to sync.
  public var bytesFoundFromSource: Swift.Int64 = Swift.Int64()

  /// Objects found only in the data sink that are scheduled to be deleted.
  public var objectsFoundOnlyFromSink: Swift.Int64 = Swift.Int64()

  /// Bytes found only in the data sink that are scheduled to be deleted.
  public var bytesFoundOnlyFromSink: Swift.Int64 = Swift.Int64()

  /// Objects in the data source that are not transferred because they already
  /// exist in the data sink.
  public var objectsFromSourceSkippedBySync: Swift.Int64 = Swift.Int64()

  /// Bytes in the data source that are not transferred because they already
  /// exist in the data sink.
  public var bytesFromSourceSkippedBySync: Swift.Int64 = Swift.Int64()

  /// Objects that are copied to the data sink.
  public var objectsCopiedToSink: Swift.Int64 = Swift.Int64()

  /// Bytes that are copied to the data sink.
  public var bytesCopiedToSink: Swift.Int64 = Swift.Int64()

  /// Objects that are deleted from the data source.
  public var objectsDeletedFromSource: Swift.Int64 = Swift.Int64()

  /// Bytes that are deleted from the data source.
  public var bytesDeletedFromSource: Swift.Int64 = Swift.Int64()

  /// Objects that are deleted from the data sink.
  public var objectsDeletedFromSink: Swift.Int64 = Swift.Int64()

  /// Bytes that are deleted from the data sink.
  public var bytesDeletedFromSink: Swift.Int64 = Swift.Int64()

  /// Objects in the data source that failed to be transferred or that failed
  /// to be deleted after being transferred.
  public var objectsFromSourceFailed: Swift.Int64 = Swift.Int64()

  /// Bytes in the data source that failed to be transferred or that failed to
  /// be deleted after being transferred.
  public var bytesFromSourceFailed: Swift.Int64 = Swift.Int64()

  /// Objects that failed to be deleted from the data sink.
  public var objectsFailedToDeleteFromSink: Swift.Int64 = Swift.Int64()

  /// Bytes that failed to be deleted from the data sink.
  public var bytesFailedToDeleteFromSink: Swift.Int64 = Swift.Int64()

  /// For transfers involving PosixFilesystem only.
  ///
  /// Number of directories found while listing. For example, if the root
  /// directory of the transfer is `base/` and there are two other directories,
  /// `a/` and `b/` under this directory, the count after listing `base/`,
  /// `base/a/` and `base/b/` is 3.
  public var directoriesFoundFromSource: Swift.Int64 = Swift.Int64()

  /// For transfers involving PosixFilesystem only.
  ///
  /// Number of listing failures for each directory found at the source.
  /// Potential failures when listing a directory include permission failure or
  /// block failure. If listing a directory fails, no files in the directory are
  /// transferred.
  public var directoriesFailedToListFromSource: Swift.Int64 = Swift.Int64()

  /// For transfers involving PosixFilesystem only.
  ///
  /// Number of successful listings for each directory found at the source.
  public var directoriesSuccessfullyListedFromSource: Swift.Int64 = Swift.Int64()

  /// Number of successfully cleaned up intermediate objects.
  public var intermediateObjectsCleanedUp: Swift.Int64 = Swift.Int64()

  /// Number of intermediate objects failed cleaned up.
  public var intermediateObjectsFailedCleanedUp: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `TransferCounters`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferCounters().with { $0.objectsFoundFromSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.TransferCounters"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
