// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// This resource represents the configuration of a transfer job that runs
/// periodically.
public struct TransferJob: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A unique name (within the transfer project) assigned when the job is
  /// created.  If this field is empty in a CreateTransferJobRequest, Storage
  /// Transfer Service assigns a unique name. Otherwise, the specified name
  /// is used as the unique name for this job.
  ///
  /// If the specified name is in use by a job, the creation request fails with
  /// an [ALREADY_EXISTS][google.rpc.Code.ALREADY_EXISTS] error.
  ///
  /// This name must start with `"transferJobs/"` prefix and end with a letter or
  /// a number, and should be no more than 128 characters. For transfers
  /// involving PosixFilesystem, this name must start with `transferJobs/OPI`
  /// specifically. For all other transfer types, this name must not start with
  /// `transferJobs/OPI`.
  ///
  /// Non-PosixFilesystem example:
  /// `"transferJobs/^(?!OPI)[A-Za-z0-9-._~]*[A-Za-z0-9]$"`
  ///
  /// PosixFilesystem example:
  /// `"transferJobs/OPI^[A-Za-z0-9-._~]*[A-Za-z0-9]$"`
  ///
  /// Applications must not rely on the enforcement of naming requirements
  /// involving OPI.
  ///
  /// Invalid job names fail with an
  /// [INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT] error.
  ///
  /// [google.rpc.Code.ALREADY_EXISTS]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Code/alreadyExists
  /// [google.rpc.Code.INVALID_ARGUMENT]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Code/invalidArgument
  public var name: Swift.String = Swift.String()

  /// A description provided by the user for the job. Its max length is 1024
  /// bytes when Unicode-encoded.
  public var description: Swift.String = Swift.String()

  /// The ID of the Google Cloud project that owns the job.
  public var projectId: Swift.String = Swift.String()

  /// Optional. The user-managed service account to which to delegate service
  /// agent permissions. You can grant Cloud Storage bucket permissions to this
  /// service account instead of to the Transfer Service service agent.
  ///
  /// Format is
  /// `projects/-/serviceAccounts/ACCOUNT_EMAIL_OR_UNIQUEID`
  ///
  /// Either the service account email
  /// (`SERVICE_ACCOUNT_NAME@PROJECT_ID.iam.gserviceaccount.com`) or the unique
  /// ID (`123456789012345678901`) are accepted in the string. The `-`
  /// wildcard character is required; replacing it with a project ID is invalid.
  ///
  /// See
  /// https://cloud.google.com//storage-transfer/docs/delegate-service-agent-permissions
  /// for required permissions.
  public var serviceAccount: Swift.String = Swift.String()

  /// Transfer specification.
  public var transferSpec: TransferSpec? = nil

  /// Replication specification.
  public var replicationSpec: ReplicationSpec? = nil

  /// Notification configuration.
  public var notificationConfig: NotificationConfig? = nil

  /// Logging configuration.
  public var loggingConfig: LoggingConfig? = nil

  /// Specifies schedule for the transfer job.
  /// This is an optional field. When the field is not set, the job never
  /// executes a transfer, unless you invoke RunTransferJob or update the job to
  /// have a non-empty schedule.
  public var schedule: Schedule? = nil

  /// Specifies the event stream for the transfer job for event-driven transfers.
  /// When EventStream is specified, the Schedule fields are ignored.
  public var eventStream: EventStream? = nil

  /// Status of the job. This value MUST be specified for
  /// `CreateTransferJobRequests`.
  ///
  /// **Note:** The effect of the new job status takes place during a subsequent
  /// job run. For example, if you change the job status from
  /// [ENABLED][google.storagetransfer.v1.TransferJob.Status.ENABLED] to
  /// [DISABLED][google.storagetransfer.v1.TransferJob.Status.DISABLED], and an
  /// operation spawned by the transfer is running, the status change would not
  /// affect the current operation.
  ///
  /// [google.storagetransfer.v1.TransferJob.Status.DISABLED]: <doc:TransferJob/Status/disabled>
  /// [google.storagetransfer.v1.TransferJob.Status.ENABLED]: <doc:TransferJob/Status/enabled>
  public var status: TransferJob.Status = TransferJob.Status()

  /// Output only. The time that the transfer job was created.
  public var creationTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time that the transfer job was last modified.
  public var lastModificationTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time that the transfer job was deleted.
  public var deletionTime: GoogleWKT.Timestamp? = nil

  /// The name of the most recently started TransferOperation of this JobConfig.
  /// Present if a TransferOperation has been created for this JobConfig.
  public var latestOperationName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TransferJob`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferJob().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let projectId = CodingKeys(stringValue: "projectId")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let transferSpec = CodingKeys(stringValue: "transferSpec")
    static let replicationSpec = CodingKeys(stringValue: "replicationSpec")
    static let notificationConfig = CodingKeys(stringValue: "notificationConfig")
    static let loggingConfig = CodingKeys(stringValue: "loggingConfig")
    static let schedule = CodingKeys(stringValue: "schedule")
    static let eventStream = CodingKeys(stringValue: "eventStream")
    static let status = CodingKeys(stringValue: "status")
    static let creationTime = CodingKeys(stringValue: "creationTime")
    static let lastModificationTime = CodingKeys(stringValue: "lastModificationTime")
    static let deletionTime = CodingKeys(stringValue: "deletionTime")
    static let latestOperationName = CodingKeys(stringValue: "latestOperationName")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "projectId",
      "serviceAccount",
      "transferSpec",
      "replicationSpec",
      "notificationConfig",
      "loggingConfig",
      "schedule",
      "eventStream",
      "status",
      "creationTime",
      "lastModificationTime",
      "deletionTime",
      "latestOperationName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    self.transferSpec = try container.decodeIfPresent(TransferSpec.self, forKey: .transferSpec)
    self.replicationSpec = try container.decodeIfPresent(
      ReplicationSpec.self, forKey: .replicationSpec)
    self.notificationConfig = try container.decodeIfPresent(
      NotificationConfig.self, forKey: .notificationConfig)
    self.loggingConfig = try container.decodeIfPresent(LoggingConfig.self, forKey: .loggingConfig)
    self.schedule = try container.decodeIfPresent(Schedule.self, forKey: .schedule)
    self.eventStream = try container.decodeIfPresent(EventStream.self, forKey: .eventStream)
    if let value = try container.decodeIfPresent(TransferJob.Status.self, forKey: .status) {
      self.status = value
    }
    self.creationTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .creationTime)
    self.lastModificationTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .lastModificationTime)
    self.deletionTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .deletionTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .latestOperationName) {
      self.latestOperationName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encodeIfPresent(self.transferSpec, forKey: .transferSpec)
    try container.encodeIfPresent(self.replicationSpec, forKey: .replicationSpec)
    try container.encodeIfPresent(self.notificationConfig, forKey: .notificationConfig)
    try container.encodeIfPresent(self.loggingConfig, forKey: .loggingConfig)
    try container.encodeIfPresent(self.schedule, forKey: .schedule)
    try container.encodeIfPresent(self.eventStream, forKey: .eventStream)
    try container.encode(self.status, forKey: .status)
    try container.encodeIfPresent(self.creationTime, forKey: .creationTime)
    try container.encodeIfPresent(self.lastModificationTime, forKey: .lastModificationTime)
    try container.encodeIfPresent(self.deletionTime, forKey: .deletionTime)
    try container.encode(self.latestOperationName, forKey: .latestOperationName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The status of the transfer job.
  public enum Status: Codable, Equatable, Sendable {
    /// Zero is an illegal value.
    case unspecified
    /// New transfers are performed based on the schedule.
    case enabled
    /// New transfers are not scheduled.
    case disabled
    /// This is a soft delete state. After a transfer job is set to this
    /// state, the job and all the transfer executions are subject to
    /// garbage collection. Transfer jobs become eligible for garbage collection
    /// 30 days after their status is set to `DELETED`.
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enabled: return 1
      case .disabled: return 2
      case .deleted: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATUS_UNSPECIFIED"
      case .enabled: return "ENABLED"
      case .disabled: return "DISABLED"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Status/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATUS_UNSPECIFIED": self = .unspecified
      case "ENABLED": self = .enabled
      case "DISABLED": self = .disabled
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Status/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enabled
      case 2: self = .disabled
      case 3: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATUS_UNSPECIFIED")
      case .enabled: return try container.encode("ENABLED")
      case .disabled: return try container.encode("DISABLED")
      case .deleted: return try container.encode("DELETED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.TransferJob"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
