// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A description of the execution of a transfer.
public struct TransferOperation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A globally unique ID assigned by the system.
  public var name: Swift.String = Swift.String()

  /// The ID of the Google Cloud project that owns the operation.
  public var projectId: Swift.String = Swift.String()

  /// Transfer specification.
  public var transferSpec: TransferSpec? = nil

  /// Notification configuration.
  public var notificationConfig: NotificationConfig? = nil

  /// Cloud Logging configuration.
  public var loggingConfig: LoggingConfig? = nil

  /// Start time of this transfer execution.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// End time of this transfer execution.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Status of the transfer operation.
  public var status: TransferOperation.Status = TransferOperation.Status()

  /// Information about the progress of the transfer operation.
  public var counters: TransferCounters? = nil

  /// Summarizes errors encountered with sample error log entries.
  public var errorBreakdowns: [ErrorSummary] = []

  /// The name of the transfer job that triggers this transfer operation.
  public var transferJobName: Swift.String = Swift.String()

  /// Initialize a new instance of `TransferOperation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferOperation().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The status of a TransferOperation.
  public enum Status: Codable, Equatable, Sendable {
    /// Zero is an illegal value.
    case unspecified
    /// In progress.
    case inProgress
    /// Paused.
    case paused
    /// Completed successfully.
    case success
    /// Terminated due to an unrecoverable failure.
    case failed
    /// Aborted by the user.
    case aborted
    /// Temporarily delayed by the system. No user action is required.
    case queued
    /// The operation is suspending and draining the ongoing work to completion.
    case suspending
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inProgress: return 1
      case .paused: return 2
      case .success: return 3
      case .failed: return 4
      case .aborted: return 5
      case .queued: return 6
      case .suspending: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATUS_UNSPECIFIED"
      case .inProgress: return "IN_PROGRESS"
      case .paused: return "PAUSED"
      case .success: return "SUCCESS"
      case .failed: return "FAILED"
      case .aborted: return "ABORTED"
      case .queued: return "QUEUED"
      case .suspending: return "SUSPENDING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATUS_UNSPECIFIED": self = .unspecified
      case "IN_PROGRESS": self = .inProgress
      case "PAUSED": self = .paused
      case "SUCCESS": self = .success
      case "FAILED": self = .failed
      case "ABORTED": self = .aborted
      case "QUEUED": self = .queued
      case "SUSPENDING": self = .suspending
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inProgress
      case 2: self = .paused
      case 3: self = .success
      case 4: self = .failed
      case 5: self = .aborted
      case 6: self = .queued
      case 7: self = .suspending
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .inProgress: return try container.encode(1)
      case .paused: return try container.encode(2)
      case .success: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .aborted: return try container.encode(5)
      case .queued: return try container.encode(6)
      case .suspending: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.TransferOperation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
