// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// TransferOptions define the actions to be performed on objects in a transfer.
public struct TransferOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// When to overwrite objects that already exist in the sink. The default is
  /// that only objects that are different from the source are overwritten. If
  /// true, all objects in the sink whose name matches an object in the source
  /// are overwritten with the source object.
  public var overwriteObjectsAlreadyExistingInSink: Swift.Bool = Swift.Bool()

  /// Whether objects that exist only in the sink should be deleted.
  ///
  /// **Note:** This option and
  /// [delete_objects_from_source_after_transfer][google.storagetransfer.v1.TransferOptions.delete_objects_from_source_after_transfer]
  /// are mutually exclusive.
  ///
  /// [google.storagetransfer.v1.TransferOptions.delete_objects_from_source_after_transfer]: <doc:TransferOptions/deleteObjectsFromSourceAfterTransfer>
  public var deleteObjectsUniqueInSink: Swift.Bool = Swift.Bool()

  /// Whether objects should be deleted from the source after they are
  /// transferred to the sink.
  ///
  /// **Note:** This option and
  /// [delete_objects_unique_in_sink][google.storagetransfer.v1.TransferOptions.delete_objects_unique_in_sink]
  /// are mutually exclusive.
  ///
  /// [google.storagetransfer.v1.TransferOptions.delete_objects_unique_in_sink]: <doc:TransferOptions/deleteObjectsUniqueInSink>
  public var deleteObjectsFromSourceAfterTransfer: Swift.Bool = Swift.Bool()

  /// When to overwrite objects that already exist in the sink. If not set,
  /// overwrite behavior is determined by
  /// [overwrite_objects_already_existing_in_sink][google.storagetransfer.v1.TransferOptions.overwrite_objects_already_existing_in_sink].
  ///
  /// [google.storagetransfer.v1.TransferOptions.overwrite_objects_already_existing_in_sink]: <doc:TransferOptions/overwriteObjectsAlreadyExistingInSink>
  public var overwriteWhen: TransferOptions.OverwriteWhen = TransferOptions.OverwriteWhen()

  /// Represents the selected metadata options for a transfer job.
  public var metadataOptions: MetadataOptions? = nil

  /// Initialize a new instance of `TransferOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferOptions().with { $0.overwriteObjectsAlreadyExistingInSink = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Specifies when to overwrite an object in the sink when an object with
  /// matching name is found in the source.
  public enum OverwriteWhen: Codable, Equatable, Sendable {
    /// Overwrite behavior is unspecified.
    case unspecified
    /// Overwrites destination objects with the source objects, only if the
    /// objects have the same name but different HTTP ETags or checksum values.
    case different
    /// Never overwrites a destination object if a source object has the
    /// same name. In this case, the source object is not transferred.
    case never
    /// Always overwrite the destination object with the source object, even if
    /// the HTTP Etags or checksum values are the same.
    case always
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .different: return 1
      case .never: return 2
      case .always: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "OVERWRITE_WHEN_UNSPECIFIED"
      case .different: return "DIFFERENT"
      case .never: return "NEVER"
      case .always: return "ALWAYS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OverwriteWhen/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "OVERWRITE_WHEN_UNSPECIFIED": self = .unspecified
      case "DIFFERENT": self = .different
      case "NEVER": self = .never
      case "ALWAYS": self = .always
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OverwriteWhen/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .different
      case 2: self = .never
      case 3: self = .always
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .different: return try container.encode(1)
      case .never: return try container.encode(2)
      case .always: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.TransferOptions"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
