// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A description of the execution of a transfer.
public struct TransferOperation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A globally unique ID assigned by the system.
  public var name: Swift.String = Swift.String()

  /// The ID of the Google Cloud project that owns the operation.
  public var projectId: Swift.String = Swift.String()

  /// Transfer specification.
  public var transferSpec: TransferSpec? = nil

  /// Notification configuration.
  public var notificationConfig: NotificationConfig? = nil

  /// Cloud Logging configuration.
  public var loggingConfig: LoggingConfig? = nil

  /// Start time of this transfer execution.
  public var startTime: GoogleWKT.Timestamp? = nil

  /// End time of this transfer execution.
  public var endTime: GoogleWKT.Timestamp? = nil

  /// Status of the transfer operation.
  public var status: TransferOperation.Status = TransferOperation.Status()

  /// Information about the progress of the transfer operation.
  public var counters: TransferCounters? = nil

  /// Summarizes errors encountered with sample error log entries.
  public var errorBreakdowns: [ErrorSummary] = []

  /// The name of the transfer job that triggers this transfer operation.
  public var transferJobName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TransferOperation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferOperation().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let projectId = CodingKeys(stringValue: "projectId")
    static let transferSpec = CodingKeys(stringValue: "transferSpec")
    static let notificationConfig = CodingKeys(stringValue: "notificationConfig")
    static let loggingConfig = CodingKeys(stringValue: "loggingConfig")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let status = CodingKeys(stringValue: "status")
    static let counters = CodingKeys(stringValue: "counters")
    static let errorBreakdowns = CodingKeys(stringValue: "errorBreakdowns")
    static let transferJobName = CodingKeys(stringValue: "transferJobName")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "projectId",
      "transferSpec",
      "notificationConfig",
      "loggingConfig",
      "startTime",
      "endTime",
      "status",
      "counters",
      "errorBreakdowns",
      "transferJobName",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    self.transferSpec = try container.decodeIfPresent(TransferSpec.self, forKey: .transferSpec)
    self.notificationConfig = try container.decodeIfPresent(
      NotificationConfig.self, forKey: .notificationConfig)
    self.loggingConfig = try container.decodeIfPresent(LoggingConfig.self, forKey: .loggingConfig)
    self.startTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(TransferOperation.Status.self, forKey: .status) {
      self.status = value
    }
    self.counters = try container.decodeIfPresent(TransferCounters.self, forKey: .counters)
    if let value = try container.decodeIfPresent([ErrorSummary].self, forKey: .errorBreakdowns) {
      self.errorBreakdowns = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .transferJobName) {
      self.transferJobName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encodeIfPresent(self.transferSpec, forKey: .transferSpec)
    try container.encodeIfPresent(self.notificationConfig, forKey: .notificationConfig)
    try container.encodeIfPresent(self.loggingConfig, forKey: .loggingConfig)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.status, forKey: .status)
    try container.encodeIfPresent(self.counters, forKey: .counters)
    try container.encode(self.errorBreakdowns, forKey: .errorBreakdowns)
    try container.encode(self.transferJobName, forKey: .transferJobName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The status of a TransferOperation.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Status: Codable, Equatable, Sendable {
    /// Zero is an illegal value.
    case unspecified
    /// In progress.
    case inProgress
    /// Paused.
    case paused
    /// Completed successfully.
    case success
    /// Terminated due to an unrecoverable failure.
    case failed
    /// Aborted by the user.
    case aborted
    /// Temporarily delayed by the system. No user action is required.
    case queued
    /// The operation is suspending and draining the ongoing work to completion.
    case suspending
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inProgress: return 1
      case .paused: return 2
      case .success: return 3
      case .failed: return 4
      case .aborted: return 5
      case .queued: return 6
      case .suspending: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATUS_UNSPECIFIED"
      case .inProgress: return "IN_PROGRESS"
      case .paused: return "PAUSED"
      case .success: return "SUCCESS"
      case .failed: return "FAILED"
      case .aborted: return "ABORTED"
      case .queued: return "QUEUED"
      case .suspending: return "SUSPENDING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Status/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATUS_UNSPECIFIED": self = .unspecified
      case "IN_PROGRESS": self = .inProgress
      case "PAUSED": self = .paused
      case "SUCCESS": self = .success
      case "FAILED": self = .failed
      case "ABORTED": self = .aborted
      case "QUEUED": self = .queued
      case "SUSPENDING": self = .suspending
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Status/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inProgress
      case 2: self = .paused
      case 3: self = .success
      case 4: self = .failed
      case 5: self = .aborted
      case 6: self = .queued
      case 7: self = .suspending
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATUS_UNSPECIFIED")
      case .inProgress: return try container.encode("IN_PROGRESS")
      case .paused: return try container.encode("PAUSED")
      case .success: return try container.encode("SUCCESS")
      case .failed: return try container.encode("FAILED")
      case .aborted: return try container.encode("ABORTED")
      case .queued: return try container.encode("QUEUED")
      case .suspending: return try container.encode("SUSPENDING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.TransferOperation"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
