// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Specifies the request passed to UpdateAgentPool.
public struct UpdateAgentPoolRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The agent pool to update. `agent_pool` is expected to specify
  /// following fields:
  ///
  /// *  [name][google.storagetransfer.v1.AgentPool.name]
  ///
  /// *  [display_name][google.storagetransfer.v1.AgentPool.display_name]
  ///
  /// *  [bandwidth_limit][google.storagetransfer.v1.AgentPool.bandwidth_limit]
  /// An `UpdateAgentPoolRequest` with any other fields is rejected
  /// with the error [INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT].
  ///
  /// [google.rpc.Code.INVALID_ARGUMENT]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Code/invalidArgument
  /// [google.storagetransfer.v1.AgentPool.bandwidth_limit]: <doc:AgentPool/bandwidthLimit>
  /// [google.storagetransfer.v1.AgentPool.display_name]: <doc:AgentPool/displayName>
  /// [google.storagetransfer.v1.AgentPool.name]: <doc:AgentPool/name>
  public var agentPool: AgentPool? = nil

  /// The [field mask]
  /// (https://developers.google.com/protocol-buffers/docs/reference/google.protobuf)
  /// of the fields in `agentPool` to update in this request.
  /// The following `agentPool` fields can be updated:
  ///
  /// *  [display_name][google.storagetransfer.v1.AgentPool.display_name]
  ///
  /// *  [bandwidth_limit][google.storagetransfer.v1.AgentPool.bandwidth_limit]
  ///
  /// [google.storagetransfer.v1.AgentPool.bandwidth_limit]: <doc:AgentPool/bandwidthLimit>
  /// [google.storagetransfer.v1.AgentPool.display_name]: <doc:AgentPool/displayName>
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `UpdateAgentPoolRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateAgentPoolRequest().with { $0.agentPool = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.UpdateAgentPoolRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
