// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request passed to UpdateTransferJob.
public struct UpdateTransferJobRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of job to update.
  public var jobName: Swift.String = Swift.String()

  /// Required. The ID of the Google Cloud project that owns the
  /// job.
  public var projectId: Swift.String = Swift.String()

  /// Required. The job to update. `transferJob` is expected to specify one or
  /// more of five fields:
  /// [description][google.storagetransfer.v1.TransferJob.description],
  /// [transfer_spec][google.storagetransfer.v1.TransferJob.transfer_spec],
  /// [notification_config][google.storagetransfer.v1.TransferJob.notification_config],
  /// [logging_config][google.storagetransfer.v1.TransferJob.logging_config], and
  /// [status][google.storagetransfer.v1.TransferJob.status].  An
  /// `UpdateTransferJobRequest` that specifies other fields are rejected with
  /// the error [INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT]. Updating a
  /// job status to
  /// [DELETED][google.storagetransfer.v1.TransferJob.Status.DELETED] requires
  /// `storagetransfer.jobs.delete` permission.
  ///
  /// [google.rpc.Code.INVALID_ARGUMENT]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Code/invalidArgument
  /// [google.storagetransfer.v1.TransferJob.Status.DELETED]: <doc:TransferJob/Status/deleted>
  /// [google.storagetransfer.v1.TransferJob.description]: <doc:TransferJob/description>
  /// [google.storagetransfer.v1.TransferJob.logging_config]: <doc:TransferJob/loggingConfig>
  /// [google.storagetransfer.v1.TransferJob.notification_config]: <doc:TransferJob/notificationConfig>
  /// [google.storagetransfer.v1.TransferJob.status]: <doc:TransferJob/status>
  /// [google.storagetransfer.v1.TransferJob.transfer_spec]: <doc:TransferJob/transferSpec>
  public var transferJob: TransferJob? = nil

  /// The field mask of the fields in `transferJob` that are to be updated in
  /// this request.  Fields in `transferJob` that can be updated are:
  /// [description][google.storagetransfer.v1.TransferJob.description],
  /// [transfer_spec][google.storagetransfer.v1.TransferJob.transfer_spec],
  /// [notification_config][google.storagetransfer.v1.TransferJob.notification_config],
  /// [logging_config][google.storagetransfer.v1.TransferJob.logging_config], and
  /// [status][google.storagetransfer.v1.TransferJob.status].  To update the
  /// `transfer_spec` of the job, a complete transfer specification must be
  /// provided. An incomplete specification missing any required fields is
  /// rejected with the error
  /// [INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT].
  ///
  /// [google.rpc.Code.INVALID_ARGUMENT]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Code/invalidArgument
  /// [google.storagetransfer.v1.TransferJob.description]: <doc:TransferJob/description>
  /// [google.storagetransfer.v1.TransferJob.logging_config]: <doc:TransferJob/loggingConfig>
  /// [google.storagetransfer.v1.TransferJob.notification_config]: <doc:TransferJob/notificationConfig>
  /// [google.storagetransfer.v1.TransferJob.status]: <doc:TransferJob/status>
  /// [google.storagetransfer.v1.TransferJob.transfer_spec]: <doc:TransferJob/transferSpec>
  public var updateTransferJobFieldMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `UpdateTransferJobRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateTransferJobRequest().with { $0.jobName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.storagetransfer.v1.UpdateTransferJobRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
